README.md
This PR fixes a typo in `README.md` where the Markdown syntax for **bold** was shown as **bold\*\*.
Before:
After:
---
Maybe this was intentional in the original text, since the latter two asterisks were escaped, but it seemed inconsistent with the rest of the text where all bold text are actually bold without using `**` literally.
Anyway, I love the concept behind `fabric`, looking forward to learning more and following the project grow.
=> Fix typo in Markdown bold

.gitignore, client/p.py, server/fabric_api_server.py, server/fabric_web_interface/fabric_web_server.py
This PR proposes the following small fixes/changes
1. Change the `fabric_web_server`and `fabric_api_server` default IP to `127.0.0.1`
2. Add `.venv/` to `.gitignore`
3. Change shebang in `client/p.py` to standard `#!/usr/bin/env python3`
=> Update .gitignore and fabric server IP configurations

README.md
In the configuration of the shell alias, the command is not working.
I have
- changed the position of single quotation marks 
- changed fabric="/the/path/to/fabric/client" to fabric="/the/path/to/fabric/client/**fabric**"
- changed .bashrc to **~/**.bashrc
=> Correct the configuration to define alias in the shell

server/fabric_api_keys.json, server/fabric_api_server.py
Here I added path and pattern mapping dictionary in the server code. This will allow the milling function more dynamic and can be easily scale as mention in #52 #64 #44 
This is not breaking change, if you try to send a HTTP call to `/extwis` you can still do it. I also add more path, `/summarize` that use summarize pattern in the pattern directory, without changing anything in the milling function.
=> feat: mapping path and pattern in the dictionary

installer/server/api/fabric_api_server.py
The lines being removed didn't seem to be used in the server code and were causing errors on package initialization. I removed them.
=> removes initialization of API keys from server

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/question.yml, .github/pull_request_template.md
This PR adds a few templates to the repo to facilitate collaboration and communication with the community of contributors and users.
Closes #109 
This is what it should look like after merged. Starting from the `New Issue` button under the `Issues` tab.
=> process enhancement: adds templates to the repo

patterns/create_command/README.md, patterns/create_command/system.md
This adds a new "create_command" pattern that generates CLI commands for any locally installed tool (including appropriate options and switches) based on a description of what the user wants the tool to do. The user describes what the specified tool should do and the documentation from the "-h" help switch that most commands have. The pattern then acts as an individual who is reading the help documentation and selecting the correct options and switches to add to the command to achieve the specified goal. 
For example, if the user wants to know how to run `sqlmap` under specific conditions, they may use `fabric` with the `create_command` pattern as follows (specify the tool, description of what the tool should do, and the help documentation via the "-h" switch for the tool):
``` …
```
=> Add New "create_command" Pattern

installer/client/cli/utils.py
I had some trouble running fabric locally due to some hard coded openai urls in the fetch_available_models functions which required having a valid OPENAI_API_KEY.
This should let fabric communicate with other open_api compliant servers.
I also threw in replacement code to use the model listing function that's included with the OpenAI class.
Finally I've added some detail to the error messages if an exception is thrown while retrieving the list of models.
=> Add code to use openai_base_url and use OpenAI's model lister function

patterns/improve_prompt/system.md
Additional instructions for Fabric to improve the prompt instead of overriding fabric's pattern with the input prompt.
When we use the original `improve_prompt` pattern to improve a prompt by, for example `cat prompt_to_be_improved.md | fabric -p improve_prompt` , Fabric interprets the text of the prompt to be improved (User input) as the actual prompt instructions, and the result is Fabric's pattern being overridden by the user input (Which is itself a prompt, hence the confusion).
I just included additional instructions at the end of the pattern's system.md to stop Fabric (OpenAI GPT LLM) from overriding the "pattern" with the user prompt
No related open issues
ISSUE: In the following image, I have a poorly written prompt, and when I use fabric's pattern "improve_prompt", it takes my …
=> Improved system.md to avoid pattern from being overridden by user input

installer/client/cli/yt.py
I've added the option to select the language in which the video is recorded on youtube and later through the script transcribed.
Default is English.
None found.
Now I can use it for example with pl language videos:
=> Language choice option when pulling a transcript from yt

installer/client/cli/yt.py
This PR adds some additional metadata to the output returned by the `yt` cli. In particular- the video id, title, channel, and publish date/time string. Example below. 
```bash
$ yt --metadata https://www.youtube.com/watch\?v\=VH3F6tdxJ6c
{
"id": "VH3F6tdxJ6c",
"title": "UL NO. 429: Build Your Career Around Problems",
"channel": "Unsupervised Learning",
"published_at": "2024-04-27T02:56:33Z"
}
```
N/A
N/A
=> feat: add metadata flag to yt cli

README.md
Broken reference link. Replaced it with new:
https://github.com/danielmiessler/fabric/tree/main/installer/client
See issue: 
https://github.com/danielmiessler/fabric/issues/366
=> Fix for broken link pointing to /client

patterns/answer_interview_question/system.md
because: As a user, I should be able to answer
interview questions quickly and effectively in realtime
this commit: Adds a pattern for answering interview questions
```
echo 'What are differences between Liveness, Readiness, and Startup Probes?' | fabric --stream --pattern answer_interview_question
"In Kubernetes, Liveness, Readiness, and Startup Probes serve distinct purposes for managing containerized applications. Liveness Probes help Kubernetes understand if an application is running; if it fails, Kubernetes restarts the container. This ensures the application is not only up but also functional. On the other hand, Readiness Probes determine if an application is ready to serve traffic. A failing Readiness Probe means the container is alive but not yet ready to accept requests, so …
```
=> Add answer interview question pattern

installer/client/cli/utils.py
Hi there,
thank you for providing fabric to the community. This PR is a little contribution to solve the following loop : setup -> no API key provided --> need to setup. The use case is to only use local models with ollama.
Feel free to do whatever you want with this btw ;)
This PR add a private function at the end of setup step to ensure .env file is created even if no API key provided. This lets user with only local models use fabric without creating useless openAPI key for example.
closes #285
=> Ensure env file created in setup when no API keys provided

installer/client/cli/save.py
This PR adds the ability to configure the date format of the target filename via setting the `SAVE_DATE_FORMAT` variable in `~/.config/fabric/.env`.
Previously, there was no way to get rid of the date being prepended to the target filename, but with this PR this is now possible by leaving `SAVE_DATE_FORMAT` empty like so:
```
SAVE_DATE_FORMAT=''
```
- Update `DATE_FORMAT` to be configurable using the `SAVE_DATE_FORMAT` environment variable
- Modify target filename generation to handle cases where `SAVE_DATE_FORMAT` is left blank
- Default to date format "%Y-%m-%d" if `SAVE_DATE_FORMAT` is not set
Prevent NoneType from ending up in the tags. The previous fix did not work and "None" would still end up in the tags if `FABRIC_FRONTMATTER_TAGS` was not specified.
None
N/A
=> Add configurable date format for save helper app

installer/client/cli/save.py
This addressed a couple of minor refactorings including, swapping a conditional and removing an unused f-string.
If it closes an issue, type `closes #493 `.
=> Refactored save.py

patterns/create_idea_compass/system.md
My PR adds the create_idea_compass pattern using the Zettelkasten method of note taking
Below is the output using Claude Opus
Here is a summary of the key points from the survey on adversarial reconnaissance techniques:
Tags:: #cybersecurity #reconnaissance #adversary #taxonomy
Date:: 04/19/2023
The paper provides a comprehensive survey and taxonomy of the techniques, tactics, and tools that adversaries use to conduct reconnaissance activities throughout the cyber attack process. It aims to categorize and understand this complex but vital aspect of cyber attacks.
Reconnaissance refers to the ongoing process used by attackers to gather as much information as possible about target systems or networks that can be used to conduct various types of malicious activity, such as gaining …
=> Added idea compass pattern

README.md, installer/client/cli/fabric.py
This removes the "NOTE: This will revert the default model to gpt4-turbo. please run --changeDefaultModel to once again set the default model" that appears (1) in the readme file, and (2) in the --help text. The note appears to reflect behavior that is no longer happening, at least, I've not observed this reversion.
If this behavior still happens, given some specific conditions, then the note should be changed (instead of removed) to call that out.
=> Removing the note about pattern updates changing the default model

patterns/analyze_email_headers/system.md
Adds a new pattern called analyze_email_headers to analyze SPF, DKIM, and DMARC in email headers.
None
=> Add pattern to analyze email headers for SPF, DKIM and DMARC

patterns/summarize_git_diff/system.md
CHANGES:
- Add intro sentence output requirement
- Emphasize succinct bullet points in CHANGES section
- Remove redundant output instruction
- Expand commit prefix list in instructions
- Add imperative mood and present tense guidelines
- Mention Deis Commit Style Guide adherence
expands on summarize_git_diff
After using `git commit -m "$(git diff --staged | fabric -p summarize_git_diff)"` for awhile I found that 
a) commits were still using past tense at times
b) would skip the intro sentence
This aims to address these issue while also providing more guidance.
=> docs: update summarize_git_diff to refine output and instruction clarity

patterns/create_cyber_summary/system.md, patterns/extract_song_meaning/system.md, patterns/official_pattern_template/system.md
Fixes a typo in the output instructions of the pattern template files. Corrects "bolt" to "bold" for clarity and consistency.
Fixes the issue #696
=> Fixed typo 'bolt' to 'bold' in pattern templates

patterns/extract_instructions/system.md
This pattern is for use with `yt --transcript`, specifically for videos from Network Chuck, David Bombal, and other tech creators. I've been using `extract_instructions` with gpt-4o as the LLM to help me along my technical learning journey.
- Adds a pattern, `extract_instructions`
This adds a system message to fabric prompting the LLM to extract the instructions from a video transcript and detail them in step-by-step, actionable goals.  The pattern is presented to the LLM in the 'official pattern tempate' formula. The goal of creating this prompt was to attempt to extract the code/commands that are often spoken aloud in tech tutorial videos and have them ordered into actionable steps.  
This pattern works amazingly with gpt-4o and is surprisingly sub optimal with claude-3.5-sonnet.
=> Addition of `extract_instructions`

.github/workflows/go.yml
Updates the GitHub Actions workflow to be triggered on tag creation.
On tag creation, it runs the regular builds, but the only difference is a final step to upload the artifacts to GitHub Releases so they are discoverable.
Also manages the Go version in a single go.mod file, rather than across two different files, where the workflow version is easily forgotten. 
Finally updates the binary names to not include the distribution.  ubuntu-latest binaries work on Fedora, so therefore it makes more sense to me to call them `linux` and `darwin`.
Closes #808
=> fix(ci): upload built binaries to GitHub Releases on tag creation

core/fabric.go, vendors/ollama/ollama.go
Fixed a possible spelling error that occurred during setup where the function SetupVendors would print "skiped" when it skipped a vendor. Changed the output to "skipped".
=> Fix spelling error in fabric.go

main.go
Changes the exit code from -1 to 1. 1 means the program terminated due to a generic error
N/A
N/A
=> fix: correct os.Exit code from -1 to 1 in main.go

core/chatter.go, core/vendors_test.go, vendors/anthropic/anthropic.go, vendors/gemini/gemini.go, vendors/ollama/ollama.go, vendors/openai/openai.go, vendors/vendor.go
In golang, contexts should be propagated downwards in order to be able
to provide features such as cancellation.
This commit refactors the Vendor interface to accept a context as a
first parameter so that it can be propagated downwards.
**Note:** If this PR is accepted, there is of course more work required to fix other places
to not create their own context but rather accept a context as a parameter.
N/A other than that `fabric` does not support cancellation signals for example.
Continuing this type of work will make it trivial to support cancellations signals
in the future.
=> refactor: accept context as parameter of Vendor.Send

README.md, cli/cli.go, cli/flags.go, core/chatter.go, core/fabric.go, core/models.go, vendors/dryrun/dryrun.go
This pull request introduces a new `--dry-run` flag to the CLI application. This flag allows users to see what would be sent to the model without actually sending the request. The changes include updates to the `README.md` for documentation purposes and modifications to the CLI code to implement the dry-run functionality.
1. **README.md**
- Added a description for the new `--dry-run` flag under the Application Options section.
2. **cli/cli.go**
- Implemented the logic for handling the `--dry-run` flag. This includes fetching the pattern and context content (if provided) and displaying the formatted request that would be sent to the model.
3. **cli/flags.go**
- Added the `DryRun` field to the `Flags` struct to accommodate the new command-line option.
```diff
Application Options:
-u, --url= …
```
=> Add dry run

README.md
-Updated the readme with env variables for Apple Silicon based mac as the path for Brew installed apps is different there.
The path on Apple Silicon based macs for brew installed go is:
`opt/homebrew/bin/go`
On Intel based macs it will be:
`/usr/local/go`
This is just a small proposal that clears it up.
=> update: add  env variable info for Apple Silicon

patterns/analyze_product_feedback/system.md
This pattern allows you to summarize, rate, and deduplicate feedback about products. It's very helpful for anyone working in product management, engineering, etc.
=> Adding new pattern: `analyze_product_feedback`.

README.md
Minor typo fix. The table of contents is broken and links to the word 'Migrating' instead of 'Migration'
N/A
N/A
=> Fix broken link in table of contents in README.md (Migrating -> Migration)

README.md
Proposal to update Readme file for a smoother setup experience, especially for users who use Golang for the first time.
Why: According to current Readme users might attempt to call `fabric --setup` before they have added the Golang environment variables.
https://github.com/danielmiessler/fabric/issues/942
=> Readme: move fabric setup after environment setup

patterns/extract_ctf_writeup/README.md, patterns/extract_ctf_writeup/system.md
I've recently started to use this as a way to decide, if i want to invest the time and watch a full video e.g. of IPPSEC doing a hackthebox machine. 
Source: https://www.youtube.com/watch?v=tQ34Ntkr7H4v
```markdown
In this Hack The Box walkthrough, IPSec demonstrates exploiting a DevOps-themed box, highlighting common developer mistakes. The main vulnerabilities include an XML External Entity (XXE) injection and an exposed SSH key, which allowed unauthorized access to the system. Learnings include the importance of securing sensitive files and validating file uploads.
- **Local File Inclusion (LFI) via XXE Injection**: No specific CVE mentioned.
- **Exposed SSH Key**: No specific CVE mentioned.
- **Insecure Direct Object Reference (IDOR)**: No specific CVE mentioned.
- **Unintended SSH …
```
=> add extract_ctf_writeup as a new pattern

README.md
This PR addresses an issue in the setup instructions for Apple Silicon Macs. The previous configuration for GOROOT pointed to '/opt/homebrew/bin/go', which resulted in an error: 'go: cannot find GOROOT directory'. 
By dynamically determining the correct GOROOT path using Homebrew's installation path, this fix ensures compatibility with M1/M2 Macs. These changes resolve the issue for users following the README on Apple Silicon Macs.
=> Fix GOROOT path for Apple Silicon Macs

README.md, cli/flags.go, cli/flags_test.go, common/domain.go, go.mod, vendors/openai/openai.go, vendors/openai/openai_test.go
Using optional seed parameter in OpenAI API to get reproducible results 
- adding -e flag to cli Flags
- propagating seed value up to go-openai.ChatCompletionRequest struct
- adding a log line (Debug level) to track system_fingerprint
- adding tests in openai and cli modules
- Even if we set the seed, we may get different results, we will have same results between two different calls only if Openai / Groq B/E status or model configuration is not changed. Changes are tracked using system_fingerprint parameter in return values.
- OpenAI relevant notes: https://platform.openai.com/docs/advanced-usage/reproducible-outputs
- Groq relevant notes: https://console.groq.com/docs/api-reference#chat
=> adding flag for pinning seed in openai and compatible APIs

db/storage.go
Trims the formatting on fabric -l, making it easier to combine with other CLI tools like fzf
This is a breaking change from the previous functionality. I also think we could combine this with a "raw" flag (ex: `fabric -l --raw`).
Let me know what you think, thanks!
=> feat: remove cli list label and indentation

patterns/solve_with_cot/system.md
Fixes typo:
> . Use a "Chain of Thought" reasoning process if necessary, breaking down y [sic]
Corrects steps under 3.c which should be underneath and not following.
=> Update patterns/solve_with_cot/system.md typos

README.md
Adds a `pbpaste` section to the Readme for Windows and Linux users. 
My linter also removed a few trailing whitespace chars.
closes #1063
=> Update README.md with pbpaste section

patterns/review_design/system.md
Adds pattern for `review_design` - pattern creates comprehensive review of provided design 
```
This document outlines the architecture of the AI Nutrition-Pro application
mermaid
C4Container
title Container diagram for AI Nutrition-Pro
Container_Boundary(c0, "AI Nutrition-Pro") {
Container(api_gateway, "API Gateway", "Kong", "Authentication of clients, filtering of input, rate limiting")
Container(app_control_plane, "Web Control Plane", "Golang, AWS Elastic Container Service", "Provides control plane to onboard and manage clients, configuration and check billing data")
ContainerDb(control_plan_db, "Control Plane Database", "Amazon RDS", "Stores all data related to control plan, tenants, billing")
Container(backend_api, "API Application", "Golang, AWS Elastic Container Service", "Provides …
```
=> feat: add review_design pattern

patterns/create_design_document/system.md
New pattern: `create_design_document` - it creates structured design document with initial description of idea or project. 
```
Dietitians use online applications to create meals, diets and calculate calories called meal planners. Different professionals have different ways of creating diets, which gives a personal style to it. LLMs can reproduce this personal style of writing based on samples of already created content. Meal planners can use LLMs to speed up diet creation for dietitians.
AI Nutrition-Pro will be backend API application that will have the possibility to integrate with any meal planner application for dietitians. It will reproduce the personal style of a …
```
=> feat: create create_design_document pattern

patterns/refine_design_document/system.md
`refine_design_document` pattern is used to refine particular design document according to review. It suppose to be used with two other pattern `create_design_document` (https://github.com/danielmiessler/fabric/pull/1070) and `review_design` (https://github.com/danielmiessler/fabric/pull/1072)
Example of usage:
PROJECT.md:
```
Dietitians use online applications to create meals, diets and calculate calories called meal planners. Different professionals have different ways of creating diets, which gives a personal style to it. LLMs can reproduce this personal style of writing based on samples of already created content. Meal planners can use LLMs to speed up diet creation for dietitians.
AI Nutrition-Pro will be backend API application that will have the possibility to integrate with any …
```
=> feat: add pattern refine_design_document

README.md
In the process of setting up patterns, we've added a step to unalias any existing alias with the same name. This ensures that our dynamically defined functions won't conflict with any pre-existing aliases.
During the setup of fabric I added the obsidian vault bits and received this error after sourcing my `~/.zshrc`
```bash
(eval):2: defining function based on alias `agility_story'
(eval):2: parse error near `()'
(eval):2: defining function based on alias `ai'
(eval):2: parse error near `()'
(eval):2: defining function based on alias `analyze_answers'
(eval):2: parse error near `()'
(eval):2: defining function based on alias `analyze_cfp_submission'
(eval):2: parse error near `()'
(eval):2: defining function based on alias `analyze_claims'
(eval):2: parse error near `()'
(eval):2: …
```
=> :sparkles: Added unaliasing to pattern setup

.github/workflows/update-version-and-create-tag.yml, flake.nix, gomod2nix.toml
Previously I added a nix flake for this project, but it requires constant `gomod2nix.toml` maintenance and as a result the reproducible fabric package provided by the flake broke when `go.mod` was updated without syncing `gomod2nix.toml`
This pull request adds automatic gomod2nix updates to the existing github workflow.
=> flake: add gomod2nix auto-update

restapi/serve.go
gin.Default() to gin.New() because `gin.Default()` already includes the Logger and Recover middleware. 
```
r.Use(gin.Logger())
r.Use(gin.Recovery())
```
=> fix: fix default gin

core/chatter.go, plugins/db/fsdb/patterns.go
This PR adds the ability to load patterns directly from files using explicit path prefixes, making it easier to test and iterate on patterns without requiring installation into the fabric config structure.
Currently, to test a pattern it needs to be instantiated in the fabric config file structure. This change allows for quicker testing and iteration of patterns directly from files.
- Adds support for loading patterns from files using explicit path prefixes
- Maintains full backwards compatibility with named patterns
- Handles common path formats:
- Relative paths (`./pattern.txt`, `../pattern.txt`)
- Home directory (`~/patterns/test.txt`)
- Absolute paths (`/path/to/pattern.txt`)
Use explicit path prefixes to distinguish file paths from pattern names:
```bash
fabric --pattern …
```
=> feat: add file-based pattern support

core/chatter.go, plugins/db/fsdb/patterns.go
- Stronger separation of concerns between chatter.go and patterns.go
- Consolidate pattern loading logic into GetPattern method
- Support both file and database patterns through single interface
- Maintain API compatibility with Storage interface
- Handle variable substitution in one place
- Keep backward compatibility for REST API through Get method
The changes enable cleaner pattern handling while maintaining existing interfaces and adding file-based pattern support.
=> refactor: unify pattern loading and variable handling

core/chatter.go
In the current version, if user is executing pattern without input, eg `fabric --pattern summarize_git_diff`, the program will panic with this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe22330]
goroutine 1 [running]:
github.com/danielmiessler/fabric/core.(*Chatter).BuildSession(0xc0004e43c0, 0xc00051e060, 0x0)
/home/gs/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.111/core/chatter.go:116 +0x3b0
github.com/danielmiessler/fabric/core.(*Chatter).Send(0xc0004e43c0, 0xc00051e060, 0xc0003f00a0)
/home/gs/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.111/core/chatter.go:30 +0x69
github.com/danielmiessler/fabric/cli.Cli({0x129b59d, 0x8}) …
```
=> fix: provide default message content to avoid nil pointer dereference

cli/flags.go, common/domain.go, core/chatter.go
Make template variable substitution in input opt-in via --input-has-vars flag
When users paste Ansible, Jekyll, or other content containing {{variable}} syntax into fabric, 
our template processor attempts to resolve these variables, leading to unwanted variable 
substitution and errors about missing variables.
- Added new --input-has-vars flag
- Template variable substitution in user input only occurs when flag is set
- All other template processing (patterns, etc.) remains unchanged
- Preserves literal curly braces by default
```bash
echo "Hello my name is {{name}}" | ./fabric -v=name:Matt
> Hello! It looks like there might have been a small error...
echo "Hello my name is {{name}}" | ./fabric -v=name:Matt --input-has-vars
> Hello Matt! How can I assist you today?
Relates to : …
```
=> Add --input-has-vars flag to control variable substitution in input

plugins/db/fsdb/patterns.go
Fix recursive variable resolution of {{input}} in patterns
This PR fixes an issue where the recursive template variable resolution system would process {{input}} placeholders prematurely during pattern processing.
The fix:
- Introduces a sentinel token approach to protect {{input}} during variable resolution
- Temporarily replaces all {{input}} occurrences with a unique sentinel string
- Processes all other template variables normally
- Restores the user input in place of each sentinel at the end
This ensures that:
1. Pattern variables are fully resolved
2. All {{input}} placements are preserved
3. User input is inserted at each {{input}} location
4. No unintended recursive processing occurs
The change is contained to the pattern processing logic and maintains compatibility with the …
=> Fix: Mask input token to prevent var substitution in patterns

cli/flags.go, cli/flags_test.go, go.mod, go.sum
This PR adds YAML configuration support to Fabric, allowing users to persist commonly used settings and share configurations. The implementation focuses on maintainability and extensibility while preserving all existing CLI functionality.
- Load settings from YAML configuration files
- Maintain proper precedence (CLI flags override YAML values)
- Type-safe parsing with reflection
- Easy extensibility through struct tags
- Added yaml tags to supported Flags struct fields
- Uses reflection to safely handle YAML-to-struct mapping
- Maintains backward compatibility with existing CLI
- Early parsing of --config flag to support proper override order
Added test cases covering:
- Basic YAML configuration loading
- CLI override behavior
- Type conversion handling
- Error cases
Added README …
=> feat: Add YAML configuration support

cli/README.md, cli/example.yaml, cli/flags.go
This fixes an issue introduced in the last feature, where the custom message was incorrectly handled.
In this usage 
echo "foo" | ./fabric --pattern ai "custom message" --dry-run
it would erroneously append --dry-run to the user input.
Added example.yaml and readme
=> Fix: Issue with the custom message and added example config file.

plugins/tools/to_pdf/to_pdf.go
This PR resolves a bug in the `to_pdf` plugin where it fails to move files across different filesystems. The issue arises from the use of the `os.Rename` function, which does not support cross-device file moves. The fix replaces `os.Rename` with a combination of `io.Copy` and `os.Remove`, ensuring compatibility with environments where /tmp and the current working directory are on different filesystems.
closes #[1221]
None
=> Fix cross-filesystem file move in to_pdf plugin (issue 1221)

plugins/tools/to_pdf/to_pdf.go
Revamp CLI argument handling and output naming logic: Rewrote command-line argument handling to support intuitive input/output resolution, added automatic `.tex` file discovery, and improved output filename generation.
- **Smart Argument Resolution**  
```go
// New logic
switch argCount {
case 0: // stdin → output.pdf
case 1: // Detect if arg is .tex input/.pdf output/name stub
case 2: // Input (with .tex fallback) + output name
}
Question #171
No screenshots
=> Added output filename support for to_pdf

plugins/ai/anthropic/anthropic.go
This PR adds support for custom API base URLs in the Anthropic plugin:
- Enable and improve custom API base URL configuration
- Add proper handling of v1 endpoint for UUID-containing URLs
- Implement URL formatting logic for consistent endpoint structure
- Clean up commented code and improve configuration flow
Testing:
- Verified base URL configuration with default endpoint
- Tested custom endpoint with UUID handling
- Confirmed proper v1 endpoint appending
=> feat(anthropic): enable custom API base URL support

cli/cli.go, cli/flags.go, plugins/tools/youtube/youtube.go
This PR adds the ability to grab the transcript of a YouTube video with timestamps. The timestamps are formatted as `HH:MM:SS` and are prepended to each line of the transcript. The feature is enabled by the new `--transcript-with-timestamps` flag, so it's similar to the existing `--transcript` flag.
Providing a summary of a video that includes timestamps for quick navigation to specific parts of the video.
Please reference any open issues this PR relates to in here - not applicable.
```
❯ ./fabric -y "https://www.youtube.com/watch?v=5DgHDANmP9M" --transcript-with-timestamps             
[00:00:07 - 00:00:10] hi uh hi everybody good afternoon thank
[00:00:09 - 00:00:13] you so much for coming to my talk …
```
=> Add the ability to grab YouTube video transcript with timestamps

core/plugin_registry.go, plugins/ai/lmstudio/lmstudio.go, restapi/configuration.go
This PR adds LM Studio compatibility. Now this can be used side by side with OpenAI no need for changing URLs in the .env file to make it work
- Added LM Studio as a new plugin, now it can be used with Fabric.
- Updated the plugin registry with the new plugin name
- Updated the configuration with the required base url
closes #[928]
A lot of credit goes to @sosacrazy126 as this is based on his solution.
1. Clone the repo `git clone https://github.com/verebes1/fabric.git`
2. Enter the project dir `cd fabric`
3. Install the project `go install`
4. Run LM Studio and its local webserver with a model of your choice
5. Run `fabric --setup` and setup your local url for LM Studio alternatively you can also add the url yourself to your .env file to fabric's settings …
=> feat: Add LM Studio compatibility

plugins/ai/vendors.go
Remove the cancellation of remaining goroutines when a vendor collection fails. This ensures that other vendor collections continue even if one fails.
Fixes listing models via `fabric -L` and using non-default models via `fabric -m custom_model`, when localhost models (e.g. Ollama, LM Studio) are not listening on a given port (basically shut down).
---
After https://github.com/danielmiessler/fabric/pull/1302, commands like `fabric -L` and `fabric -m` hang indefinitely if LM Studio is not setup. With this change, it will only print error and proceed further with the other configured vendors:
```shell
❯ fabric -L
LM Studio failed to send request: Get "http://localhost:1234/v1/models": dial tcp 127.0.0.1:1234: connect: connection refused
Ollama Get "http://localhost:11434/api/tags": dial tcp …
```
=> fix: continue fetching models even if some vendors fail

Web Interface MOD Readme Files/WEB V2 Install Guide.md, Web Interface MOD Readme Files/pr-1284-update.md
Layout of  Web instalI md file did not process correctly in previous pull. 
cd web
npm install 
npx svelte-kit sync
became "cd web npm install npx svelte-kit sync"
Fixed in this pull to prevent user confusion.
=> Update Web V2 Install Guide layout

main.go, plugins/ai/azure/azure_test.go
N/A
Fabric fails to compile:
```plain
$ go install .
./version.go:3:5: version redeclared in this block
./main.go:12:5: other declaration of version
```
The `version` string is set up in `version.go` and does not need to be declared again
```go
package main
var version = "v1.4.153"
```
```plain
kayvan@dharma src/fabric [03-08-extra-version-declaration-removed] $ go install .
kayvan@dharma src/fabric [03-08-extra-version-declaration-removed] $ fabric --version
v1.4.153
```
=> Fix: v1.4.153 does not compile because of extra version declaration

restapi/contexts.go, restapi/patterns.go, restapi/sessions.go
- Remove explicit type parameters from StorageHandler initialization
- Update contexts handler constructor implementation
- Update patterns handler constructor implementation
- Update sessions handler constructor implementation
- Simplify API by relying on type inference
This PR removes explicit type parameters from `NewStorageHandler` function calls in three REST API handler implementations: contexts, patterns, and sessions. The change simplifies the code by relying on Go's type inference capabilities.
N/A
This change leverages Go's type inference capabilities to simplify the code. Since the `NewStorageHandler` function can infer the type parameter from the provided arguments, explicitly specifying the type parameter is unnecessary. This makes the code cleaner and more maintainable while …
=> Remove Generic Type Parameters from StorageHandler Initialization

cli/cli.go
This PR fixes an issue where changes to the default model were not being persisted to the environment file. Now, after setting up the default model, we explicitly save the environment file to ensure changes are preserved.
closes #1353 
```plaintext
$ grep DEFAULT ~/.config/fabric/.env 
DEFAULT_VENDOR=OpenAI
DEFAULT_MODEL=gpt-4o
kayvan@thor ~ $ fabric -d
Available models:
[...]
[136]   tts-1
[137]   computer-use-preview
[138]   o1
[Default]
Enter the index the name of your default model (leave empty for 'gpt-4o' or type 'reset' to remove the value):
o1
Enter model context length (leave empty to skip):
DEFAULT_VENDOR: OpenAI
DEFAULT_MODEL: o1
```
However, looking at `.env` we still see:
```plaintext
$ grep DEFAULT ~/.config/fabric/.env
DEFAULT_VENDOR=OpenAI
DEFAULT_MODEL=gpt-4o
```
Running …
=> Fix Default Model Change Functionality

patterns/raycast/yt
If you use a youtube link like `https://youtu.be/sHIlFKKaq0A` percentEndcoding encodes the link to `https%3A%2F%2Fyoutu.be%2FsHIlFKKaq0A`, which throws an error in fabric.
With percentEndcoding false, the script receives the link without encoding and works.
https://github.com/danielmiessler/fabric/issues/1075
=> fix: set percentEncoded to false

README.md
Fabric has been packaged in Homebrew (macOS, Linux) and AUR (Arch Linux, and Arch-like distributions).
- Homebrew: `arm64_sequoia`, `arm64_sonoma`, `arm64_ventura`, `sonoma`, `ventura`, `x86_64_linux`
- AUR: `x86_64`, `aarch64`
This adds instructions to install Fabric using native OS package managers.
Closes #274, #812.
N/A
=> Add installation instructions for OS package managers

web/src/lib/components/chat/DropdownGroup.svelte
Hi!
This PR adds support for the Italian language in the language selection dropdown for the Web GUI.
As an Italian, I thought this could be useful for others as well.
I modified the array of supported languages by adding the last one (Italian):
```typescript
const languages = [
{ code: '', name: 'Default Language' },
{ code: 'en', name: 'English' },
{ code: 'fr', name: 'French' },
{ code: 'es', name: 'Spanish' },
{ code: 'de', name: 'German' },
{ code: 'zh', name: 'Chinese' },
{ code: 'ja', name: 'Japanese' },
{ code: 'it', name: 'Italian' }
];
```
I tested this locally, and it seems to work without any issues.
Additionally, the Fabric CLI correctly recognizes Italian as a valid option.
However, since this project uses Svelte and TypeScript, which I'm not deeply familiar with, I’d really …
=> feat: add it lang to the chat drop down menu lang in web gui

restapi/chat.go, restapi/serve.go, restapi/strategies.go, web/Web Interface Update README Files/pr-1284-update.md, web/src/lib/components/chat/DropdownGroup.svelte, web/src/lib/interfaces/chat-interface.ts, web/src/lib/services/ChatService.ts, web/src/lib/store/strategy-store.ts, web/static/strategies/strategies.json
Strategies, when selected, prepend the pattern prompt as per the cli implementation. 
**Frontend (Svelte Web UI)**
web/src/lib/store/strategy-store.ts
**Created a Svelte store to manage the list of strategies and the selected strategy.**
Fetches the list from the static file /strategies/strategies.json.
web/static/strategies/strategies.json
**Created a static manifest listing all available strategies (name + description).**
Used by the frontend dropdown to populate options.
web/src/lib/components/chat/DropdownGroup.svelte
**Added a new dropdown for "Prompt Strategy".**
Binds to the selected strategy store.
Fetches and displays strategies from the static manifest.
web/src/lib/services/ChatService.ts
**Modified to include the selected strategy name in chat POST requests.** …
=> Strategy flag enhancement - Web UI implementation 

Dockerfile
Updates the base Go image from 1.23.3 to 1.23.4 to match the minimum required Go version specified in the `go.mod` file
Without this PR the Docker image fails to build with the error
```bash
=> ERROR [builder 4/6] RUN go mod download                                                                                                                                                                                                                                                            0.1s
------
> [builder 4/6] RUN go mod download:
0.101 go: go.mod requires go >= 1.23.4 (running go 1.23.3; GOTOOLCHAIN=local)
```
=> Update Dockerfile so that Go image version matches go.mod version

README.md
- Add contributors section with visual representation
- Include link to project contributors page
- Add attribution to contrib.rocks tool
This pull request adds a "Contributors" section to the `README.md` file, utilizing the `contrib.rocks` service to visually display project contributors.
N/A
Clicking on the image leads to the project contributors page on GitHub: https://github.com/danielmiessler/fabric/graphs/contributors
=> docs: add contributors section to README with contrib.rocks image

README.md, core/plugin_registry.go, plugins/ai/grokai/grokai.go, plugins/ai/grokai/grokai_test.go, restapi/configuration.go
Integrate the Grok AI provider into the Fabric system for AI model interactions.
* Add Grok AI client to the plugin registry.
* Include Grok AI API key in REST API configuration endpoints.
* Updated README note.
This pull request adds support for GrokAI as a new AI plugin in the fabric project. The changes include the addition of a new plugin client for GrokAI, integration into the plugin registry, and updates to the configuration handler to manage GrokAI API keys.
closes #1412
`fabric -L` now shows this:
Also, tested by having it write most of this PR:
- **core/plugin_registry.go**: Updated to include the GrokAI plugin in the registry.
- **plugins/ai/grokai/grokai.go**: New file added to define the GrokAI client, leveraging compatibility with the OpenAI client.
- …
=> feat: add Grok AI provider support

plugins/db/fsdb/storage.go
A Fabric pattern is made up of a directory in `~/.config/fabric/patterns` where the name of the directory represents the pattern name. Within that directory are one or more `.md` files that describe the pattern.
With the current implementation that uses `os.Remove`, invoking the `DELETE /patterns/:name` API results in the following error
```bash
"could not delete test: remove /Users/sherif/.config/fabric/patterns/test: directory not empty"
```
since [`os.Remove`](https://pkg.go.dev/os#Remove) will only delete files or **empty** directories.
This PR replaces `os.Remove` with [`os.RemoveAll`](https://cs.opensource.google/go/go/+/go1.24.2:src/os/path.go;l=73) that deletes the specified path and any children it contains
This ensures that patterns can be deleted whilst also maintaining …
=> Fix error in deleting patterns due to non empty directory

core/plugin_registry.go, plugins/ai/cerebras/cerebras.go, plugins/ai/cerebras/cerebras_test.go
- Introduce Cerebras AI plugin import in plugin registry.
- Register Cerebras client in the NewPluginRegistry function.
This PR adds support for Cerebras AI to the Fabric CLI, enabling users to access models hosted on the Cerebras platform.
N/A - Rework of https://github.com/danielmiessler/fabric/pull/1424
N/A
- **core/plugin_registry.go**: Updated to include the Cerebras plugin in the list of AI plugins and instantiate its client in the plugin registry.
- **plugins/ai/cerebras/cerebras.go**: A new file was added to define the Cerebras client, leveraging the OpenAI-compatible client structure for seamless integration.
- **plugins/ai/cerebras/cerebras_test.go**: New file added with unit tests to validate the initialization and configuration of the Cerebras client.
- In …
=> feat: add Cerebras AI plugin to plugin registry

restapi/strategies.go
- Add `Prompt` field to `StrategyMeta` struct.
- Include `strings` package for filename processing.
- Derive strategy name from filename using `strings.TrimSuffix`.
- Store `Prompt` value from JSON data in `StrategyMeta`
This pull request updates the `/strategies` endpoint implementation to include a `prompt` field in the strategy metadata returned by the API. It also derives the `name` of each strategy from the filename rather than relying on a `name` field in the JSON files.
closes #1423 
- **Added**: Import of the `strings` package.
- **Changed**: The `StrategyMeta` struct now includes a `Prompt` field.
- **Changed**: The anonymous struct used for unmarshaling strategy metadata in the file reader loop now includes a `Prompt` field and omits the `Name` field.
- **Changed**: The `Name` …
=> feat: enhance StrategyMeta with Prompt field and dynamic naming

common/groups_items.go
Enhances the GroupsItemsSelector Print method by adding case-insensitive alphabetical sorting for both groups and items, improving user navigation and experience.
Changes include:
- Add case-insensitive alphabetical sorting for groups
- Add case-insensitive alphabetical sorting for items within each group
- Preserve original ordering stability using sort.SliceStable
- Improve code organization with separate sorting steps for groups and items
This pull request introduces alphabetical sorting (case-insensitive) for both groups and items within the `GroupsItemsSelector` struct's `Print` method in the `common` package. The changes ensure a more organized and user-friendly output when displaying grouped items.
- **common/groups_items.go**: Modified to include sorting functionality for groups …
=> feat: Alphabetical case-insensitive sorting for groups and items

core/plugin_registry.go, plugins/ai/vendors.go
This pull request introduces two primary changes:
1. Reorders the plugins listed under the "Tools" group within the plugin registry.
2. Ensures that AI model names from each vendor are sorted alphabetically (case-insensitive) before being grouped and added to the model list.
Closes #1430 
- **Change:** Modified the order in which plugins are added to the "Tools" group.
- **Before:** 
```go
groupsPlugins.AddGroupItems("Tools", o.Defaults, o.PatternsLoader, o.YouTube, o.Language, o.Jina, o.Strategies)
```
- **After:** 
```go
groupsPlugins.AddGroupItems("Tools", o.Defaults, o.Jina, o.Language, o.PatternsLoader, o.Strategies, o.YouTube)
```
- **Reason:** This matches the list that is printed (whose indexes are then used to access the plugins in `fabric -S` interactions).
- **Change:** …
=> chore: fix fabric setup mess-up introduced by sorting lists (tools and models)

core/chatter.go, plugins/template/extension_executor.go
- refactor BuildSession raw mode to prepend system to user content
- ensure raw mode messages always have User role
- keep existing user message when no `systemMessage` provided
- append systemMessage separately in non-raw mode sessions
- Store original `cmd.Env` before context-based exec command creation
- recreate exec command with context then restore `originalEnv`
- add comments clarifying raw vs non-raw handling behavior
This PR introduces two primary changes:
1. Updates the logic in `core/chatter.go` for handling system and user messages in "raw" mode, ensuring the system message is prepended to the user input and always marked as a user message.
2. Fixes environment variable propagation in `plugins/template/extension_executor.go` when executing commands with context, ensuring the …
=> chore: Fix user input handling when using raw mode and `--strategy` flag

go.mod, go.sum, plugins/ai/anthropic/anthropic.go
- Upgrade Anthropic SDK from alpha.11 to beta.3
- Update API endpoint from v1 to v2
- Replace anthropic.F() with direct assignment
- Replace anthropic.F() with anthropic.Opt() for optional params
- Simplify event delta handling in streaming
- Change client type from pointer to value type
- Update comment with SDK changelog reference
This PR updates the Anthropic Go SDK from v0.2.0-alpha.11 to v0.2.0-beta.3 and adapts our code to the breaking changes introduced in the new SDK version. The main changes include switching from v1 to v2 API endpoints and updating the client method signatures to match the new SDK requirements.
- Updated the Anthropic SDK dependency from v0.2.0-alpha.11 to v0.2.0-beta.3
- Added the corresponding checksum entry in go.sum
- Changed the client type from pointer to …
=> chore: update Anthropic SDK to v0.2.0-beta.3 and migrate to V2 API

nix/pkgs/fabric/default.nix
Add the completion scripts to the nix package build output so that completion works on supported shells.
None
Build output puts the completion files in the output where nix expects them.
```
$ tree result/
result/
├── bin
│   ├── code_helper
│   ├── fabric
│   └── to_pdf
└── share
├── bash-completion
│   └── completions
│       └── fabric.bash
├── fish
│   └── vendor_completions.d
│       └── fabric.fish
└── zsh
└── site-functions
└── _fabric
```
Screenshot shows tab completion working with Zsh after installing the package from my fork.
=> Add completion to the build output for Nix

NOTES.md, Pattern_Descriptions/README_Pattern_Descriptions_and_Tags_MGT.md, Web Interface MOD Readme Files/pr-1284-update.md, patterns/write_nuclei_template_rule/system.md, web/README.md, web/Web Interface Update README Files/pr-1284-update.md
This pull request primarily addresses minor spelling and grammar corrections across multiple documentation files to improve clarity and professionalism. Below is a summary of the most important changes, grouped by theme.
* Corrected "Anthropric" to "Anthropic" in `NOTES.md` to fix a vendor name typo.
* Fixed "prefered" to "preferred" in `Pattern_Descriptions/README_Pattern_Descriptions_and_Tags_MGT.md` to ensure proper spelling.
* Corrected "Cummulative" to "Cumulative" and "functionnalities" to "functionalities" in `Web Interface MOD Readme Files/pr-1284-update.md` and `web/Web Interface Update README Files/pr-1284-update.md`. [[1]](diffhunk://#diff-7e3e4ed53eca1945bf427479a8fa23c9ee53824d7b20845d910c656ff340fb7aL1-R1) [[2]](diffhunk://#diff-d3811c7360c4cd7a554a22f8283b3397111b43aac9a0b06 …
=> Typos, spelling, grammar and other minor updates

plugins/ai/ollama/ollama.go
This PR allows to add a Authentication Bearer to ollama server.
It could be usefull for third party integration client that provide a remote and authentifcated ollama api access like OpenwebUi
https://docs.openwebui.com/getting-started/api-endpoints/#-ollama-api-proxy-support
https://github.com/danielmiessler/fabric/issues/1472
=> add authentification for ollama instance

web/src/lib/config/environment.ts, web/src/routes/chat/+server.ts, web/vite.config.ts
This PR introduces centralized environment configuration management for the Fabric web application. The main change is making the Fabric base URL configurable through environment variables instead of being hardcoded to `localhost:8080`. This enhancement improves deployment flexibility and follows configuration best practices.
N/A - This simple change makes it possible to point instances of the frontend Web UI to a more powerful machine on the network running Fabric (or even a cloud instance).
- **`web/src/lib/config/environment.ts`** - New centralized configuration module that handles environment variable access for both server and client contexts
- **`web/src/routes/chat/+server.ts`** - Minor whitespace cleanup (trailing spaces removed)
- **`web/vite.config.ts`** - Updated to use …
=> Web UI: Centralize Environment Configuration and Make Fabric Base URL Configurable

plugins/ai/ollama/ollama.go
This pull request introduces a configurable HTTP timeout for Ollama API requests within the `ollama.go` file. It adds a new setup question allowing users to specify a custom HTTP timeout duration with validation and default handling.
- **plugins/ai/ollama/ollama.go**: Modified to include a new configuration option for setting an HTTP timeout for Ollama API requests.
- Added a setup question `ApiHttpTimeout` which allows users to specify the desired HTTP request timeout duration.
```go
ret.ApiHttpTimeout = ret.AddSetupQuestionCustom("HTTP Timeout", true,
"Specify HTTP timeout duration for Ollama requests (e.g. 30s, 5m, 1h)")
ret.ApiHttpTimeout.Value = "20m"
```
- Modified the `configure` function to parse and apply this custom timeout value:
```go
timeout := 20 * time.Minute // Default …
```
=> fix: Add configurable HTTP timeout for Ollama client

README.md, plugins/tools/youtube/youtube.go
This PR updates Fabric's YouTube functionality to clarify that `yt-dlp` is now the primary requirement for transcript extraction, while the YouTube API key is only needed for optional features like comments and metadata extraction.
Added a new update note to inform users about the YouTube transcription changes and requirements.
- Updated package documentation to clarify requirements
- Modified setup description to be more explicit about what each component does
- Added validation to ensure API key is present when needed for comments/metadata
- Removed unnecessary service initialization from `GetVideoOrPlaylistId`
```diff
+>June 11, 2025
+>
+> - Fabric's YouTube transcription now needs `yt-dlp` to be installed. Make sure to install the latest
+>   version (2025.06.09 as of this note). The …
```
=> feat: cleanup after `yt-dlp` addition

plugins/db/fsdb/patterns.go, plugins/db/fsdb/patterns_test.go
This PR adds a `Save` method to the `PatternsEntity` struct in the FSDB (filesystem database) plugin, enabling programmatic creation and storage of patterns. The implementation includes comprehensive unit tests to ensure reliability.
Closes #1515 
- **plugins/db/fsdb/patterns.go**: Added a new `Save` method to persist pattern content to the filesystem
- **plugins/db/fsdb/patterns_test.go**: Added unit tests for the new `Save` method
Added a new method to save patterns:
```go
func (o *PatternsEntity) Save(name string, content []byte) (err error) {
patternDir := filepath.Join(o.Dir, name)
if err = os.MkdirAll(patternDir, os.ModePerm); err != nil {
return fmt.Errorf("could not create pattern directory: %v", err)
}
patternPath := filepath.Join(patternDir, o.SystemPatternFile)
if err = …
```
=> Fix REST API pattern creation

.github/workflows/update-version-and-create-tag.yml
This PR adds concurrency control and improves git synchronization to the GitHub Actions workflow that handles automatic version updates and tag creation. The changes prevent race conditions when multiple workflow runs are triggered and ensure the workflow always operates on the latest state of the repository.
Closes #1501 
- **.github/workflows/update-version-and-create-tag.yml**: Added concurrency group configuration and enhanced git synchronization steps to prevent conflicts and ensure the workflow operates on the latest repository state.
```yaml
concurrency:
group: version-update
cancel-in-progress: false
```
This ensures only one instance of the version update workflow runs at a time, preventing race conditions when multiple commits trigger the workflow simultaneously.
```yaml
- name: …
```
=> Fix: Prevent race conditions in versioning workflow.

cli/flags.go, core/chatter.go, plugins/ai/dryrun/dryrun.go
This PR refactors the message handling logic across multiple components to improve code clarity and fix issues with attachment processing. The main changes include simplifying conditional logic in `BuildChatRequest`, improving multi-content message handling in raw mode, and enhancing the dry-run plugin's output formatting for better debugging.
The changes improve code clarity by simplifying conditional logic and fixing issues with pattern-based message handling and multi-content message support in the dry-run plugin.
closes #1544 
Dry-Run now works too (before, it did not show anything as INPUT)
- **Simplified conditional logic**: Inverted the attachment check to reduce nesting and improve readability
- **Reordered message creation**: Moved the plain message creation to an `else if` block …
=> Update Message Handling for Attachments and Multi-Modal content

.github/workflows/release.yml
This PR improves the error handling in the GitHub Actions release workflow by properly checking if a release already exists before attempting to create it. The previous implementation could fail when the release view command returned a non-zero exit code.
This ensures that during the GitHub release before matrix builds start, we get only one build trying to create a release.
Closes #1554 
- `.github/workflows/release.yml`: Modified the release creation logic to properly handle the case where a release tag already exists.
The release creation step has been refactored from a single line command to a proper conditional check:
**Before:**
```yaml
gh release view ${{ env.latest_tag }} || gh release create ${{ env.latest_tag }} --title "Release ${{ env.latest_tag }}" --notes "Automated release …
```
=> fix: Race condition in GitHub actions release flow

chat/chat.go, cli/flags.go, common/domain.go, common/domain_test.go, core/chatter.go, go.mod, go.sum, nix/pkgs/fabric/gomod2nix.toml, plugins/ai/anthropic/anthropic.go, plugins/ai/azure/azure.go, plugins/ai/bedrock/bedrock.go, plugins/ai/dryrun/dryrun.go, plugins/ai/dryrun/dryrun_test.go, plugins/ai/exolab/exolab.go, plugins/ai/gemini/gemini.go, plugins/ai/lmstudio/lmstudio.go, plugins/ai/ollama/ollama.go, plugins/ai/openai/openai.go, plugins/ai/openai/openai_test.go, plugins/ai/perplexity/perplexity.go, plugins/ai/vendor.go, plugins/db/fsdb/sessions.go, plugins/db/fsdb/sessions_test.go, plugins/template/sys_test.go, restapi/chat.go, restapi/ollama.go, restapi/strategies.go
This PR updates the OpenAI integration in the Fabric project to use the official OpenAI Go SDK (`github.com/openai/openai-go`) instead of the third-party library (`github.com/sashabaranov/go-openai`). This change improves maintainability and ensures better compatibility with OpenAI's API.
Both these issues, #1549 and #1551, require using the Responses API (not the ChatCompletions API).
- **chat/chat.go**: New internal package containing chat message types and structures previously imported from the external library. Implements custom JSON marshaling/unmarshaling to handle the `Content` and `MultiContent` fields properly.
- **cli/flags.go**: Updated imports to use the new internal `chat` package
- **common/domain.go**: Updated to use internal chat types
- **common/domain_test.go**: Updated …
=> feat: Migrate to official openai-go SDK

.github/workflows/release.yml
This PR addresses cross-platform compatibility issues in the GitHub Actions release workflow by explicitly specifying the bash shell for a command that was previously failing on Windows runners.
Closes #1561 
- `.github/workflows/release.yml`: Added explicit shell specification and minor formatting adjustment
1. **Formatting adjustment** (line 5):
```yaml
- types: [ tag_created ]
+ types: [tag_created]
```
Minor formatting change removing spaces inside brackets for consistency.
2. **Shell specification added** (line 111):
```yaml
- name: Create release if it doesn't exist
+ shell: bash
env:
GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Added explicit `shell: bash` directive to ensure the step runs with bash shell across all platforms.
The "Create release if it doesn't exist" step was likely …
=> Fix Cross-Platform Compatibility in Release Workflow

core/plugin_registry.go, plugins/db/fsdb/db.go, plugins/db/fsdb/patterns.go, plugins/db/fsdb/patterns_test.go, plugins/tools/custom_patterns/custom_patterns.go, plugins/tools/custom_patterns/custom_patterns_test.go
This pull request adds support for custom patterns directories in the Fabric application, allowing users to specify an external directory for storing and loading custom patterns alongside the default patterns. The implementation includes proper plugin registration, environment variable support, and comprehensive test coverage.
Closes #1567 #1404 #972 #331
- Added import for the new `custom_patterns` plugin
- Integrated `CustomPatterns` plugin into the registry structure
- Added plugin to the setup flow and environment file management
- Added support for `CUSTOM_PATTERNS_DIRECTORY` environment variable
- Implemented home directory expansion for custom patterns path
- Extended `PatternsEntity` to include custom patterns directory configuration
- Modified `getFromDB()` to check custom …
=> Add Custom Patterns Directory Support

README.md
This PR introduces a dedicated custom patterns directory feature that allows users to create and manage personal patterns separately from Fabric's built-in patterns. The implementation provides a clean separation between user-created patterns and the core pattern library, ensuring custom patterns persist through updates.
- **README.md**: Updated documentation to reflect the new custom patterns functionality, replacing the previous manual workflow with an automated setup process.
The documentation changes include:
1. **Enhanced Table of Contents**: Added three new subsections under "Custom Patterns":
```markdown
- [Setting Up Custom Patterns](#setting-up-custom-patterns)
- [Using Custom Patterns](#using-custom-patterns)
- [How It Works](#how-it-works)
```
2. **Replaced Manual Process**: …
=> Document Custom Patterns Directory Support

plugins/tools/custom_patterns/custom_patterns.go
Fixed a configuration issue in the CustomPatterns plugin where the `IsConfigured()` method was not properly initializing configuration values from environment variables before checking if the plugin was configured.
- **plugins/tools/custom_patterns/custom_patterns.go**: Modified the `IsConfigured()` method to ensure proper configuration loading before validation.
Added a call to `Configure()` at the beginning of the `IsConfigured()` method:
```go
func (o *CustomPatterns) IsConfigured() bool {
// First configure to load values from environment variables
o.Configure()
// Check if the plugin has been configured with a directory
return o.CustomPatternsDir.Value != ""
}
```
The change adds two lines:
1. A comment explaining the purpose of the configuration call
2. A call to `o.Configure()` to …
=> Fix to persist the CUSTOM_PATTERNS_DIRECTORY variable

plugins/ai/openai/chat_completions.go, plugins/ai/openai/openai.go
This pull request adds conditional logic to prevent setting the `TopP` parameter when its value is 0 (zero) in OpenAI API requests. The change affects both chat completions and general response parameter building functions.
Closes #1588 
- **`plugins/ai/openai/chat_completions.go`**: Modified the `buildChatCompletionParams` function to conditionally set the `TopP` parameter
- **`plugins/ai/openai/openai.go`**: Modified the `buildResponseParams` function to conditionally set the `TopP` parameter
```go
// Before
ret.TopP = openai.Float(opts.TopP)
// After  
if opts.TopP != 0 {
ret.TopP = openai.Float(opts.TopP)
}
```
```go
// Before
ret.TopP = openai.Float(opts.TopP)
// After
if opts.TopP != 0 {
ret.TopP = openai.Float(opts.TopP)
}
```
Both changes follow the same pattern as the existing …
=> Do not pass non-default TopP values

internal/plugins/ai/openai_compatible/direct_models_call.go, internal/plugins/ai/openai_compatible/providers_config.go
This pull request adds support for the Together AI provider and implements a fallback mechanism for fetching models from OpenAI-compatible APIs that return non-standard response formats. The changes include a new direct API call method and enhanced model listing functionality.
Closes #1602 
```text
$ git diff --staged | summarize_git_diff -m deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free
<think>
Okay, so I need to figure out the major changes and upgrades from the given Git diff.
Let's look at the input files.
First, there's a new file added: direct_models_call.go. It contains a function DirectlyGetModels which seems
to fetch models directly from an API. The function constructs a URL, makes a GET request, handles
different response formats (OpenAI and Together), and parses the JSON …
```
=> Together AI Support with OpenAI Fallback Mechanism Added

internal/cli/chat.go, internal/cli/example.yaml, internal/cli/flags.go, internal/cli/flags_test.go, internal/core/chatter.go, internal/core/chatter_test.go, internal/domain/domain.go, internal/domain/think.go, internal/domain/think_test.go
This pull request implements a new feature to suppress "thinking" output from Claude models. The feature allows users to hide internal reasoning text that appears between configurable start and end tags (defaulting to `<think>` and `</think>`), while still displaying the final response to the user.
Closes #1458 
- **internal/cli/chat.go**: Modified output logic to handle suppressed thinking mode
- **internal/cli/example.yaml**: Added configuration examples for the new thinking suppression feature
- **internal/cli/flags.go**: Added new command-line flags and YAML configuration options for thinking suppression
- **internal/cli/flags_test.go**: Added test coverage for the new thinking suppression flags
- **internal/core/chatter.go**: Implemented core logic to suppress streaming output and …
=> Feature: Optional Hiding of Model Thinking Process with Configurable Tags

.vscode/settings.json, internal/tools/youtube/timestamp_test.go, internal/tools/youtube/youtube.go
This pull request implements intelligent duplicate content filtering for YouTube VTT (WebVTT) subtitle processing. The changes introduce time-based deduplication logic that preserves legitimate repeated content (like choruses or recurring phrases) while filtering out immediate duplicates caused by VTT formatting issues.
Closes #1614 
Closes #1632 
```text
fabric-v1.4.258 -y 'https://www.youtube.com/watch?v=mzSjAxYCEow' --transcript-with-timestamps | wc -l
5132
fabric -y 'https://www.youtube.com/watch?v=mzSjAxYCEow' --transcript-with-timestamps | wc -l
1711
```
And even without transcript timestamps:
```text
fabric-v1.4.258 -y 'https://www.youtube.com/watch?v=mzSjAxYCEow' | wc -c
192314
fabric -y 'https://www.youtube.com/watch?v=mzSjAxYCEow' | wc -c
64128
```
- **Added**: New words to the …
=> YouTube VTT Processing Enhancement

.vscode/settings.json, internal/plugins/ai/exolab/exolab.go
This pull request adds API key configuration support to the Exolab AI plugin and updates the VS Code spell checker dictionary to include the new "openaiapi" term.
Closes #1622 
- `.vscode/settings.json`: Added "openaiapi" to the spell checker dictionary
- `internal/plugins/ai/exolab/exolab.go`: Added API key setup question to the Exolab client configuration
```json
"openaiapi",
```
Added the term "openaiapi" to the `cSpell.words` array to prevent spell checker warnings.
```go
ret.ApiKey = ret.AddSetupQuestion("API Key", false)
```
Added a new setup question for API key configuration.
Prevents the following abort when trying to set up exolabs:
1. **Improved User Experience**: The setup process now guides users through both URL and authentication configuration
2. **Consistency**: Aligns the …
=> Fix abort in Exo-Labs provider plugin; with credit to @sakithahSenid

internal/plugins/ai/ollama/ollama.go
Added "mistral" to the list of model prefixes that require raw mode in the Ollama AI plugin. This is a single-line addition to support Mistral models when using the Ollama integration.
Closes #1636 
- **`internal/plugins/ai/ollama/ollama.go`**: Added "mistral" to the `ollamaPrefixes` slice in the `NeedsRawMode` function.
In the `NeedsRawMode` function, the `ollamaPrefixes` slice was updated to include Mistral models:
```go
ollamaPrefixes := []string{
"llama3",
"llama2",
+   "mistral",
}
```
This change ensures that any model name starting with "mistral" will be identified as requiring raw mode processing.
This change extends support for Mistral models in the Ollama plugin. The `NeedsRawMode` function appears to determine which models require special handling (raw mode) based on their name …
=> chore: update `NeedsRawMode` to include `mistral` prefix for Ollama

cmd/generate_changelog/incoming/1641.txt, web/vite.config.ts
This pull request increases the proxy timeout configuration in the Vite development server from 30 seconds to 15 minutes (900,000ms) for API requests and pattern/model/session name endpoints.
Closes #1604
- **web/vite.config.ts**: Modified proxy timeout settings for development server configuration
The changes involve updating two proxy configurations in the Vite config file:
1. **API proxy timeout update**:
```typescript
'/api': {
target: FABRIC_BASE_URL,
changeOrigin: true,
- timeout: 30000,
+ timeout: 900000,
rewrite: (path) => path.replace(/^\/api/, ''),
```
2. **Patterns/models/sessions proxy timeout update**:
```typescript
'^/(patterns|models|sessions)/names': {
target: FABRIC_BASE_URL,
changeOrigin: true,
- timeout: 30000,
+ timeout: 900000,
```
The timeout increase from 30 seconds …
=> Fix Fabric Web timeout error

.github/workflows/release.yml, cmd/generate_changelog/incoming/1647.txt
This pull request refactors the version retrieval mechanism in the GitHub Actions release workflow. The changes replace OS-specific git tag commands with a unified approach that reads version information directly from a Nix configuration file.
- `.github/workflows/release.yml`: Modified the version retrieval step in the release workflow to use a single, cross-platform approach instead of separate OS-specific implementations.
The most significant change is the replacement of two separate version retrieval steps with a single unified step:
**Removed:**
```yaml
- name: Get latest tag
if: matrix.os != 'windows-latest'
id: get_latest_tag
run: |
latest_tag=$(git tag --sort=-creatordate | head -n 1)
echo "latest_tag=$latest_tag" >> $GITHUB_ENV
- name: Get latest tag
if: matrix.os == …
```
=> Simplify Workflow with Single Version Retrieval Step

.vscode/settings.json, CHANGELOG.md, cmd/generate_changelog/incoming/1649.txt, internal/core/plugin_registry.go, internal/plugins/ai/ollama/ollama.go, scripts/docker-test/README.md, scripts/docker-test/base/Dockerfile, scripts/docker-test/test-runner.sh
This PR fixes an issue where Fabric would attempt to initialize and call Ollama and Bedrock APIs even when they weren't properly configured, resulting in confusing error messages during model listing operations. The changes implement proper configuration checks to ensure only explicitly configured API providers are initialized.
Closes #1195 
Closes #1645
Closes #1648 
- **Change**: Added new spell check words: `adduser`, `testuser`, `unconfigured`
- **Reason**: Supporting new test infrastructure and terminology used in the fix
- **Change**: Enhanced `hasAWSCredentials()` function to require both AWS credentials AND `BEDROCK_AWS_REGION` environment variable
- **Reason**: Prevents Bedrock client initialization when AWS credentials exist for other purposes but Bedrock isn't specifically …
=> Fix Conditional API Initialization to Prevent Unnecessary Error Messages

.github/workflows/release.yml, .vscode/settings.json, cmd/generate_changelog/incoming/1673.txt, go.mod, go.sum, internal/cli/flags.go, internal/domain/domain.go, internal/plugins/ai/anthropic/anthropic.go, internal/plugins/ai/anthropic/anthropic_test.go
This PR refactors the GitHub Actions release workflow to improve build reliability and adds support for the Claude Opus 4.1 model. The main changes include separating the version retrieval into its own job, simplifying OS detection logic, fixing parameter conflicts for Anthropic models, and updating the anthropic-sdk-go dependency.
- **.github/workflows/release.yml**: Restructured the release workflow to separate concerns and improve maintainability
- **cmd/generate_changelog/incoming/1673.txt**: Added changelog entry documenting these changes
- **go.mod / go.sum**: Updated anthropic-sdk-go dependency from v1.4.0 to v1.7.0
- **internal/plugins/ai/anthropic/anthropic.go**: Added Claude Opus 4.1 model support and fixed parameter handling
The workflow now has a dedicated `get_version` job …
=> Add Support for Claude Opus 4.1 Model

.github/workflows/release.yml
Grant write permissions to the GITHUB_TOKEN for the update_release_notes job in the release workflow to enable updating GitHub Releases (release notes) during the pipeline.
- .github/workflows/release.yml
- Added a job-level permissions block to allow writing to repository contents for the update_release_notes job.
In the update_release_notes job, explicitly request write permissions for repository contents:
```yaml
jobs:
update_release_notes:
needs: [build, get_version]
runs-on: ubuntu-latest
permissions:
contents: write
steps:
- name: Checkout code
uses: actions/checkout@v4
```
- The update_release_notes job needs to create or update release notes via the GitHub API, which requires contents: write. Without this explicit permission, the default GITHUB_TOKEN may only have read access, …
=> Grant GITHUB_TOKEN write permissions for release notes job

cmd/generate_changelog/incoming/1686.txt, internal/plugins/ai/openai/openai.go
Stop forwarding the final ResponseOutputTextDone text payload in streaming responses to prevent duplicated output. The OpenAI Responses API sends the full accumulated text again in the “done” event; since we already stream all deltas, emitting the final text duplicates content. We now ignore the final text and rely on the stream closing to signal completion.
Closes #1684 
- internal/plugins/ai/openai/openai.go
- Modified sendStreamResponses to no longer send the final text on ResponseOutputTextDone events. Added an explanatory comment.
- In sendStreamResponses, replace emitting the final text with a no-op:
```go
case string(constant.ResponseOutputTextDone("").Default()):
// The Responses API sends the full text again in the
// final "done" event. Since we've already streamed all
// delta …
```
=> Prevent duplicate text output in OpenAI streaming responses

README.md, cmd/generate_changelog/incoming/1687.txt, completions/_fabric, completions/fabric.fish, internal/cli/flags.go, internal/plugins/ai/gemini/gemini.go, internal/plugins/ai/gemini/gemini_test.go
Add first-class web search tool support for Gemini models behind the existing --search flag, with optional location controls, and append standardized citations to Gemini responses. Update CLI help text, README, and shell completions to reflect Gemini support.
Closes #1656
Before change:
```text
fabric --search -m gemini-2.5-flash 'What are the top three news items for today?'
I am sorry, but I do not have access to real-time news feeds or current events. My knowledge base was last updated at a specific point in time, and I cannot provide information on "today's" top three news items.
To find out the top news items for today, I recommend checking reputable news sources such as:
*   **Major News Websites:** BBC News, Reuters, Associated Press, The New York Times, The Wall Street Journal, …
```
=> Add Web Search Tool Support for Gemini Models

cmd/generate_changelog/incoming/1689.txt, completions/_fabric, completions/fabric.bash, completions/fabric.fish, completions/setup-completions.sh, docs/Shell-Completions.md
Improve and generalize shell completion support for the fabric CLI across Zsh, Bash, and Fish by:
- Supporting both binary names: `fabric` and `fabric-ai`
- Removing hardcoded binary references inside completion functions
- Adding an automated setup script to install completions into standard locations with sudo fallback and dry-run support
- Adding documentation with manual and automated install instructions, symlink guidance, and troubleshooting tips
This makes completions more robust, easier to install, and consistent regardless of how the binary is named.
- completions/_fabric
- Zsh completion now supports both `fabric` and `fabric-ai`, and dynamically calls the actual invoked binary for data-driven suggestions.
- completions/fabric.bash
- Bash completion now derives the invoked …
=> Enhanced Shell Completions for Fabric CLI Binaries

README.md, cmd/generate_changelog/incoming/1695.txt, completions/setup-completions.sh, docs/Shell-Completions.md
Add “no-clone” install support for shell completions by teaching the setup script to fetch completion files from GitHub when they are not present locally. Update README and docs with a one-liner install, dry-run support, and an environment variable to override the download source.
- README.md
- Added a “Quick install (no clone required)” section under Shell Completions with:
- A one-liner install command (curl | sh).
- Optional dry-run and override source examples.
- completions/setup-completions.sh
- Enhancements:
- Auto-download completion files (_fabric, fabric.bash, fabric.fish) if not found locally.
- Support for overriding download base via FABRIC_COMPLETIONS_BASE_URL.
- Added curl/wget fallback downloader and GitHub URL “blob/tree” → “raw” conversion.
- Temporary directory handling …
=> Introduce One-Liner Curl Install for Completions

cmd/generate_changelog/incoming/1717.txt, internal/cli/listing.go, internal/plugins/ai/models.go, internal/plugins/ai/models_test.go
Highlight default AI vendor/model in the interactive models listing and wire the CLI to pass configured defaults into the listing. Introduces a subtle formatting change to the non-shell-completion output and adds a unit test to verify default model highlighting.
Closes #446 
- internal/cli/listing.go
- Passes configured default vendor and model to the models listing for interactive display.
- internal/plugins/ai/models.go
- Changes the signature of PrintWithVendor to accept default vendor/model and visually marks the default in interactive listings.
- Adds case-insensitive matching for defaults.
- internal/plugins/ai/models_test.go
- Adds a unit test to ensure the default vendor/model is marked in the listing output.
- Signature change to include defaults and documentation update:
```go …
```
=> Highlight default vendor/model in model listing

README.md, cmd/generate_changelog/incoming/1718.txt, completions/_fabric, completions/fabric.bash, completions/fabric.fish, docs/Using-Speech-To-Text.md, internal/cli/flags.go, internal/log/log.go, internal/plugins/ai/openai/openai_audio.go, internal/plugins/ai/vendors.go, internal/plugins/template/extension_registry.go, internal/plugins/template/template.go
Introduce configurable, leveled debug logging across the CLI and key subsystems, replace ad-hoc/debug globals with a unified internal logging package, and expand Speech-To-Text (STT) documentation. Adds a `--debug` flag with four levels (off, basic, detailed, trace), integrates logging into transcription workflows (including ffmpeg chunking), updates shell completions, and removes the `FABRIC_STT_DEBUG` environment variable.
Closes #1220 
- README.md
- Documented `--debug` flag and the available debug levels.
- cmd/generate_changelog/incoming/1718.txt
- Changelog entry for this PR.
- completions/_fabric
- zsh completion for `--debug` with supported values.
- completions/fabric.bash
- bash completion: added `--debug` flag to options and value suggestions.
- completions/fabric.fish
- fish …
=> Implement Configurable Debug Logging Levels

README.md, cmd/generate_changelog/incoming/1723.txt, internal/plugins/ai/openai_compatible/providers_config.go
Add native support for the Venice AI provider (OpenAI-compatible) and update documentation:
- Introduce Venice AI to the OpenAI-compatible provider map with its API base URL.
- Update README with a new “Recent Major Feature” entry for Venice AI support.
- Add a Windows PowerShell one-liner for installing Fabric.
- Add “Debug Levels” to the README table of contents.
- Include a changelog stub for PR #1723.
Closes #610 
Closes #1187 
- internal/plugins/ai/openai_compatible/providers_config.go
- Added Venice AI provider configuration.
- README.md
- Added v1.4.294 feature note for Venice AI.
- Added PowerShell install snippet for Windows.
- Added “Debug Levels” entry to the Usage section of the Table of Contents.
- cmd/generate_changelog/incoming/1723.txt
- New changelog entry describing the …
=> docs: update README with Venice AI provider and Windows install script

cmd/generate_changelog/incoming/1727.txt, internal/plugins/ai/anthropic/anthropic.go
This PR replaces direct stderr output with structured debug logging for Anthropic API beta feature failures, improving the consistency of error handling and debug output across the codebase.
Closes #1724 
You can still see the warning when using the `--debug` flag
```text
fabric -m $MODEL_CLAUDE --debug 1 test
DEBUG: Anthropic beta feature context-1m-2025-08-07 failed: POST "https://api.anthropic.com/v1/messages": 400 Bad Request (Request-ID: req_011CST94aNKdnaLbUmGY7Mjf) {"type":"error","error":{"type":"invalid_request_error","message":"The long context beta is not yet available for this subscription."},"request_id":"req_011CST94aNKdnaLbUmGY7Mjf"}
I understand you want me to execute instructions using your input "test" and respond only in en-US English.
```
- …
=> Standardize Anthropic Beta Failure Logging

.github/workflows/docker-publish-on-tag.yml, .github/workflows/update-version-and-create-tag.yml, cmd/generate_changelog/incoming/1735.txt
This PR updates the Docker build configuration and modifies the version update workflow triggers. The changes ensure the Docker build process uses the correct Dockerfile location and adjusts which file changes trigger the version update and tagging workflow.
- `.github/workflows/docker-publish-on-tag.yml`: Added explicit Dockerfile path for the Docker build action
- `.github/workflows/update-version-and-create-tag.yml`: Removed markdown files from the ignore list for workflow triggers
Added a new `file` parameter to specify the Dockerfile location:
```yaml
@@ -101,6 +101,7 @@ jobs:
uses: docker/build-push-action@v6
with:
context: .
+          file: ./scripts/docker/Dockerfile
push: true
```
This explicitly tells the Docker build action to use the Dockerfile located at …
=> Fix Docker Build Path Configuration

.github/workflows/release.yml, cmd/generate_changelog/incoming/1741.txt
This PR updates the GitHub Actions release workflow to support both manual and automated release triggers by making the changelog generation more flexible in how it determines the release tag.
- `.github/workflows/release.yml` - Modified the changelog generation step to handle different trigger scenarios
The key change is in the "Update Release Description" step:
```yaml
run: go run ./cmd/generate_changelog --release ${{ github.ref_name }}
run: go run ./cmd/generate_changelog --release ${{ github.event.client_payload.tag || github.ref_name }}
```
This change uses GitHub's logical OR operator (`||`) to first check for `github.event.client_payload.tag` and fall back to `github.ref_name` if the payload tag is not available.
This modification enables the release workflow to work correctly in …
=>  CI: Fix Release Description Update
