- README.md
Headshot for Daniel linked to Scott, and vice versa.
> Update README.md - fix contributor URLs

- client/utils.py
- patterns/label_and_rate/system.md
- server/fabric_api_server.py
- server/fabric_web_interface/fabric_web_server.py
This PR focuses exclusively on updating and refining the documentation throughout the codebase. There are no functional changes to the code itself.
Changes:
📜 Updated Docstrings: Ensured that all functions, classes, and modules have clear and informative docstrings in accordance with PEP 257.
🧠 Smart Generation: Understands your code! Recognizes classes, functions, and generates crisp documentation.
📜 Modified Files: Please review before merging.
/server/fabric_api_server.py
/server/fabric_web_interface/fabric_web_server.py
/client/p.py
/client/utils.py
🙏 Request:
Please review the changes to ensure that the documentation is clear, accurate, and adheres to our project's standards.
Any feedback regarding areas that might still need clarification or additional details would be highly …
> [Snorkell.ai] Please review the generated documentation

- patterns/explain_docs/system.md
This PR adds the word that appears to be missing from this system prompt.
> added missing word to prompt instruction

- client/fabric/fabric.py
- client/fabric/utils.py
This function adds compatibility to Visual Studio Community edition.
> Update utils.py - This is a utility function standalone.get_cli_input()

- client/fabric/utils.py
Added Class Transcribe with method youtube which accepts a video id as a parameter.  Returns the transcript.
> Update utils.py with a class to transcribe YouTube Videos

- client/fabric/utils.py
Changed sys.stdin.readline().strip() to sys.stdin.read().strip() to allow multiple line input.
> Update utils.py to get_cli_input Line 192

- patterns/agility_story/system.md
- patterns/compare_and_contrast/system.md
- Add user story and acceptance criteria for agility story patterns
- Add compare and contrast system and user patterns
> Add patterns

- patterns/analyze_incident/system.md
- patterns/improve_writing/system.md
Added 1 pattern (improve_writing) which improve the writing and returns it in the native language of the input
Added 1 pattern (analyze_incident) which analyses incident articles and produces a neat and simple output (Taken from the YT Video that Daniel was in by David B
> Add 2 patterns

- installer/client/cli/README.md
Updates a broken link due to the latest folder reorg.
> fixes readme link on CLI instructions

- README.md
Changes `Create` to `Creating` for the sake of verb form consistency.
> Makes a minor README edit for the sake of consistency

- installer/client/cli/fabric.py
Ensures that when the users lists the available patterns, they are presented in alphabetical order. Helps find the desired pattern faster.
N/A
Before:
After:
>  Alphabetically sort patterns list

- patterns/extract_predictions/system.md
Fix a minor typo in the extract_predictions pattern.
None known.
> Minor typo in extract_predictions

- README.md
- installer/client/cli/fabric.py
- installer/client/cli/utils.py
- patterns/create_command/README.md
- patterns/create_threat_model/system.md
- patterns/create_visualization/system.md
- patterns/extract_article_wisdom/README.md
- patterns/extract_wisdom/README.md
Assorted typo and spelling corrections.
n/a
n/a
> Assorted typo and spelling corrections.

- patterns/analyze_tech_impact/system.md
This PR adds a new pattern named analyze_tech_impact to the Fabric repository. This pattern is designed to help users systematically analyze the impact of technology on society, environment, ethics, and policy. It encourages a deep dive into the multifaceted effects of technological innovations, providing a structured approach to understand both the positive contributions and the potential risks of new technologies.
None
None
> Added analyze_tech_impact pattern for assessing the impact of technology

- patterns/write_semgrep_rule/system.md
> Fixed typo

- helpers/yt.py
Add a language option to helpers/yt.py to get a transcript in other languages.
closes #134
no screenshots
> add language option to yt.py

- installer/client/cli/utils.py
Move code related to openai inside the try block
Note: the current implementation of the code allows the use of copy and output only when using openai
[Bug]: --copy parameter throwing an error #197
NA
> Fix bug in sendMessage by moving code

- installer/client/cli/utils.py
Looks like my previous pr got clobbered https://github.com/danielmiessler/fabric/pull/189#issuecomment-1992514728
> Add code to use openai_base_url and use OpenAI's model lister function

- installer/client/cli/utils.py
Anthropic has just released a new model Claude 3 Haiku.
- https://www.anthropic.com/news/claude-3-haiku
This PR adds support for it.
It's a small change and there is no related issue.
> feat: Add support for Claude 3 Haiku

- patterns/improve_academic_writing/system.md
- patterns/improve_writing/system.md
Fix the format in improve_writing (turn it into markdown) and add improve_academic_writing
> Fix the format in improve_writing and add improve_academic_writing

- patterns/create_network_threat_landscape/system.md
- patterns/create_network_threat_landscape/user.md
New pattern named create_network_threat_landscape that takes two bullet point lists of port and service information (non-identifiable info) and creates a report finding that details the nature of identified ports/services, risks, and more.
Output contains the following sections:
- **Description**
- **Risk**
- **Recommendations**
- **One-Sentence-Summary**
- **Trends**
- **Quotes**
_port-stats.txt_ **contains**:
- 2x IPs had RTSP open
- 40x IPs had HTTP open
- 18/24 Ports were 443/TCP
- 8/24 Ports were 80/TCP
**It should be noted that the only thing that matters is that the text you pass contains two bullet point lists of port and service information.**
`cat port-stats.txt | fabric -sp create_network_threatlandscape`
`./nmap-analysis.py fabric-report -gf nmap_output.xml`
This will …
> New Port Scan Analysis Pattern (create_network_threat_landscape)

- installer/client/cli/yt.py
adds the ability to pipe youtube video urls via stdin on yt helper
> modified yt to also accept urls via stdin

- helper_files/README.md
- installer/client/cli/ws.py
Created a helper for scrapping websites using beautiful soup to pipe into fabric.
> Webscraper

- README.md
Add an example about extracting wisdom from a Youtube video much like Daniel Miessler shows in the original intro video.
This closes no open issues. I just saw an opportunity for improvement.
When I watched the intro videos of this project I naturally got excited to try it. It took me far too long to get the example of extracting valuable information from a Youtube video working because the information in the intro video is outdated already. Daniel used a utility called "pt" which is now called "yt". It's a subtle PR but one that might might get others to try out a great example pattern of Fabric sooner.
> Add an example about extracting wisdom from a Youtube video

- helper_files/README.md
- installer/client/cli/yt.py
Adds `--comments` flag to yt helper which retrieves all comments associated with the video URL. Comments are sorted by newest first and replies are included, indenting showing nest level.
Updated helpers  README doc (and fixed some MD formatting errors) as well.
> PR - Added YT user comments retrieval to yt.py helper

- installer/client/cli/yt.py
Fixes Latin-1 decode problems
Fixes Latin-1 decode problems
For example, https://youtu.be/f2BjFilLDqQ threw a Latin-1 decode error.
Old behaviour: 
New behavior
> Fixed Latin-1 decode problems

- README.md
- installer/client/cli/fabric.py
- patterns/write_nuclei_template_rule/system.md
1. Navigate to `https://www.exploit-db.com/exploits/52001` copy the content.
```
pwnmachine@PD % pbpaste | fabric -p write_nuclei_template_rule --model gpt-4-turbo-2024-04-09
```yaml
id: CVE-2024-31621
info:
name: Flowise 1.6.5 - Authentication Bypass
author: Maerifat Majeed
severity: critical
description: |
Flowise version <= 1.6.5 is vulnerable to an authentication bypass vulnerability due to case-insensitive path handling in its middleware.
Attackers can bypass authentication by changing the case of the API path.
http:
- method: GET
path:
- "{{BaseURL}}/API/V1/credentials"
- "{{BaseURL}}/Api/V1/credentials"
- "{{BaseURL}}/aPI/v1/credentials"
matchers:
- type: status
status:
- 200
- type: word
words:
- "user_id"
- "session_token"
part: body
condition: or
```
```
Please reference any …
> Pattern for Nuclei Template

- README.md
* Disentangles copypasta that snuck into the `Custom Patterns` and `Agents` sections of the README.
* Makes a few minor copy edits in the same sections.
> Disentangle PraisonAI references in README

- patterns/to_flashcards/system.md
Adds a new pattern for Fabric to create flashcards for spaced repetition memory trainers such as Anki. This would help to remember details over a long time. This pattern was developed by [L-M-Sherlock](https://github.com/L-M-Sherlock) and presented at [Reddit](https://www.reddit.com/r/Anki/comments/11306zf/ankigpt_teach_cahtgpt_to_create_cards_for_you/), I just adapted it for Fabric.
Here is how I used this pattern. For the generated cards to be importable to Anki, they need to be in the CSV format, so the instructions include that.
```
$ pbpaste | fabric -p to_flashcards
What can change the color of glass?,"Certain elements or chemicals mixed with sand"
How can glass be strengthened?,"Through thermal tempering or chemical processes"
What is thermal tempering?,"A process to heat and cool …
```
> A new pattern to create flashcards from texts

- README.md
It's just an update to README, showing how to point to your own server.
Closes #324 , showing how to connect to another server
> Update README.md for #324

- patterns/summarize_git_diff/system.md
CHANGES:
- New system.md file created for summarizing git diffs
- Detailed steps for summarizing Git diffs outlined.
- Emphasis on creating concise, impactful update bullets.
- Introduction of conventional commits for clear change tracking.
N/A
None, but the commit for this change was created with the help of this pattern 🎉
> feat: introduced pattern for Git diff summaries

- README.md
Fixes Typo in Required Python Version of README
> Update README.md Typo

- patterns/analyze_debate/system.md
Adds a pattern that analyzes debates. Inspired by a debate that stretched over 200 messages in the amazing UL community Discord.
> added analyze_debate

- patterns/create_better_frame/system.md
Line 67 said: "When our frames our different,..."
Changed it to say: "When our frames are different,..."
This fixes a single very small type-o in the Create_Better_Frames system.md file.
N/A
N/A
> Create_Better_Frames - "Our" to "Are"

- installer/client/cli/helper.py
- patterns/analyze_patent/system.md
Add pattern analyze_patent
Adds a new pattern called analyze_patent which (as is evident from the name) analyzes the text (claims and description) of a patent. The output is: field of technology; the problem being addressed; the advantages provided; assessment of novelty; assessment of inventive step; summary of the patent; keywords describing the main concept.
Not applicable
Not applicable
> Add new pattern analyze_patent + bugfix in helper.py

- patterns/create_stride_threat_model/system.md
Pattern to create STRIDE-based threat model for cybersecurity.
```
Here is a threat model for the AI Nutrition-Pro application architecture:
THREAT SCENARIOS
- Attacker gains access to API keys and makes unauthorized API calls
- Attacker exploits vulnerability in API Gateway to bypass authentication 
- Attacker exploits vulnerability in API application to access sensitive data
- Attacker exploits vulnerability in control plane to modify configurations
- Attacker gains access to AWS environment and accesses RDS databases
- Attacker exploits vulnerability in meal planner app to upload malicious content 
- Attacker exploits vulnerability in ChatGPT integration to manipulate responses
- Insider threat - admin abuses privileges to access sensitive data
- Denial of service attack overwhelms API …
```
> feat: add create_stride_threat_model pattern

- patterns/create_git_diff_commit/README.md
- patterns/create_git_diff_commit/system.md
This pull request adds a new pattern that will use the output of a git diff or git show HEAD and create the git commands to commit those changes to the current repo.
New pattern, does not correct any issues.
> added create_git_diff_commit pattern

- README.md
- patterns/coding_master/system.md
This simply adds a coding_master pattern (and no I am not a troll)
> Create coding_master pattern

- patterns/write_nuclei_template_rule/system.md
Avoid possible confusion by the AI with typos and bad formatting
closed #524
> fix typos and formatting in nuclei template rule

- patterns/tweet/system.md
Created Tweet Monster Pattern
Any help would be great to make it better.
> Created Tweet Monster Pattern

- README.md
I noticed some of the links to sections are broken.
> Fix anchor links in README

- patterns/analyze_logs/system.md
This adds a new pattern `analyze_logs` the pattern defines a prompt for log analysis.
*Note* - when used with a real log file make sure you have enough tokens in your rate limits as you will quickly use them all.
> Add pattern for analyzing logs

- patterns/create_pattern/system.md
This pull request includes a pattern to create new fabric patterns
> feat: add create_pattern pattern

- patterns/extract_business_ideas/system.md
> Minor spelling for extract business ideas

- patterns/create_stride_threat_model/system.md
Improve `create_stride_threat_model` pattern
```markdown
The following data and assets need protection in the AI Nutrition-Pro system:
1. Dietitians' content samples stored in the API database
2. Request and response data related to LLM interactions stored in the API database
3. Control plane data (tenant information, billing data, configuration) stored in the Control Plane Database
4. API keys used for authentication of Meal Planner applications
5. Access credentials for the ChatGPT-3.5 LLM service
The following trust boundaries are identified in the AI Nutrition-Pro system:
1. Between the Meal Planner application and the API Gateway
2. Between the API Gateway and the API Application
3. Between the API Application and the ChatGPT-3.5 LLM service
4. Between the Web Control Plane and the …
```
> feat: improve create_stride_threat_model pattern

- installer/client/cli/utils.py
Updates the Claude models to use 3.5 Sonnet instead of 3.0 Sonnet. Since the API costs are identical, there are few use cases for the older model, so it has been replaced instead of adding the new model to the array.
> Update utils.py to support Claude 3.5 Sonnet

- patterns/create_coding_project/README.md
- patterns/create_coding_project/system.md
Adds a pattern called "create_coding_project"
Net new feature add. No issues being closed.
No screenshots. See README.md for example.
> Add create_coding_project Pattern

- patterns/analyze_paper/system.md
> fix (grammar)

- patterns/create_5_sentence_summary/system.md
> fix: typo in system.md

- patterns/create_5_sentence_summary/system.md
Fix a typo ("OUPTUP") and a language error ("it's" -> "its")
> Update system.md - Typo, language error

- patterns/extract_wisdom/system.md
Added missing language back to the HABITS step.
> Fix missing text in the HABITS step (extract_wisdom)

- patterns/create_logo/system.md
Thanks for all of your work!
This PR fixes a few punctuation typos in `create_logo`:
* removes a stray quotation mark
* adds a missing period for consistency
* adds a missing hyphen
* changes a hyphen to an em-dash
N/A.
N/A.
> Fix some typos in create_logo

- patterns/analyze_spiritual_text/system.md
This PR fixes a few typos in `analyze_spiritual_text`'s `system.md`:
- tenants -> tenets
- a handful of punctuation edits
N/A.
N/A. Reviewing the diff will probably be clearest.
Thank you!
> Fix some typos in analyze_spiritual_text

- patterns/summarize_lecture/system.md
I wanted to share the personal pattern I created for my learning path. 
This pattern is called 'summarize_lecture' and it should summarize the course's lecture from its transcripts. 
Hopefully it could help other people except me :)
None 
Not necessary
> added my personal pattern for summarize my course lectures

- patterns/create_tags/system.md
Add a pattern which takes input text and generates a list of space separated tags relevant to the input. Especially useful for tagging in apps like Obsidian
Tested using gpt-3.5-turbo, gpt-4, gpt-4o
None
None
> Create system.md for create_tags pattern

- patterns/extract_article_wisdom/README.md
fixed curl commands - are they obsolete?
fixed some links
> Update extract article wisdom README.md

- patterns/clean_text/system.md
This is a very simple pull to get my "pull request" feet wet! 😄 
This adds a single line to the `clean_text` pattern that instructs the llm add capitalization, paragraphs, and other formatting. This makes the output  much more readable and works well with youtube transcripts.
(The following is using `meta-llama/llama-3-70b-instruct` as the model for both outputs.)
```
yt "https://www.youtube.com/watch?v=8f5DKSx_nEE" | fabric -p clean_text
```
```
Here is the properly formatted text:
this is NASA's Boeing crew flight test mission, it the very first flight of astronauts aboard Starliner to the International Space Station. The past 24 hours have been a testament to what it's about in human space flight and really all the hard work that they've poured into this spacecraft over many years to …
```
> Update patterns\clean_text\system.md to improve text cleaning instructions

- patterns/summarize_paper/system.md
> Fixed minor typo in the summarise_paper pattern.

- patterns/create_sigma_rules/system.md
Add a pattern which takes a cybersecurity related publication and extracts TTP indicators in the form of Sigma rules. 
https://github.com/SigmaHQ/sigma
none
none
> Add create_sigma_rules Pattern

- patterns/write_hackerone_report/README.md
- patterns/write_hackerone_report/system.md
This adds the `write_hackerone_report` pattern to assist with generating HackerOne reports.
> Adding write_hackerone_report

- patterns/extract_article_wisdom/README.md
inserted "you" into "...to forget the stuff read, watch, or listen to" so that it reads "...to forget the stuff you read, watch, or listen to"
Inserted "you" into "...to forget the stuff read, watch, or listen to" so that it reads "...to forget the stuff you read, watch, or listen to"
N/A
N/A
> Update patterns/extract_article_wisdom/README.md, missing word for clarity

- patterns/write_hackerone_report/system.md
> Typoooooo My bad Daniel

- patterns/create_mermaid_visualization_for_github/system.md
Add a mermaid diagram creator that renders nicely on github ... For an E.g. 
https://gist.github.com/idvorkin/81085d6533e29c3c38b23a1dd012b1bf
> Add a mermaid diagram that can render in github markdown readmes

- patterns/create_formal_email/system.md
Added a Pattern to Create / Respond to Email, in a formal fashion.
> feat: add a pattern to draft or respond to an email

- patterns/explain_math/README.md
- patterns/explain_math/system.md
explain_math is a pattern designed to help you understand mathematical concepts in a clear and engaging way
Tested using gpt-3.5-turbo, gpt-4, gpt-4o
> create explain_math pattern

- patterns/extract_jokes/system.md
What this Pull Request (PR) does
Add a pattern which takes input text and extracts a list of jokes with punchlines.
Related issues
none
Screenshots
none
Tested using gpt-3.5-turbo, gpt-4, gpt-4o
> Create system.md for extract_jokes pattern

- README.md
Removes a duplicate usage block in the readme
> remove duplicate usage

- .github/workflows/ci.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
- db/contexts_test.go
- db/db_test.go
- db/patterns_test.go
- db/sessions_test.go
- db/storage_test.go
> test: Implement db unit tests

- core/fabric.go
- vendors/groc/groq.go
> Fix groq spelling

- common/configurable.go
- core/chatter_test.go
- core/fabric.go
- core/fabric_test.go
- core/models_test.go
- core/vendors_test.go
- vendors/vendor.go
Implement unit tests for core package
> test: core

- cli/cli.go
- cli/flags.go
- go.mod
- go.sum
- youtube/youtube.go
Rework and integration of https://github.com/danielmiessler/yt to fabric
New CLI parameters would be:
-y, --youtube=                 YouTube video url to grab transcript, comments from it and send to chat
--transcript                  Grab transcript from YouTube video and send to chat
--comments                Grab comments from YouTube video and send to chat
> feat: native integration of yt to fabric

- cli/flags.go
This fixes shadowing the original error so that the original error is
propagated upwards
Shadowing original error
N/A
> fix: shadowing original error

- cli/flags_test.go
fix: usage with deprecated elements
> fix: usage with deprecated elements

- patterns/transcribe_minutes/system.md
This pattern takes in a transcript from a meeting, and outputs minute, actionables and decisions.
The intended workflow is to record your meetings  on your phones recorder app and get a transcript. Google Pixel does this automatically, others can use Whisper to get the transcript.
No related open issues.
I cannot provide screenshots of my  meeting minutes because they are confidential. However, it has been tested on several of my work meetings and works as expected.
> Add a pattern for extracting minutes from a transcribed meeting.  

- patterns/analyze_debate/system.md
- patterns/analyze_malware/system.md
- patterns/create_quiz/system.md
- patterns/extract_business_ideas/system.md
- patterns/summarize_newsletter/system.md
Great code and prompts!
I have just fixed some typos and grammar mistakes.
Please see the explanation in each commit for details.
Best Regards,
HB
> Typo fixed

- patterns/extract_skills/system.md
Hi, I would like to add a new pattern "extract_skills" for extracting skills from job description.
> add new pattern extract_skills

- core/fabric.go
- vendors/siliconcloud/siliconcloud.go
This Pull Request adds [SiliconCloud](https://cloud.siliconflow.cn/) support.
> Add SiliconCloud support

- core/fabric.go
- go.mod
- go.sum
- vendors/mistral/mistral.go
This pull request adds [mistral.ai](https://mistral.ai) support for fabric.
> add mistral vendor

- README.md
- cli/flags.go
Corrects the description for `-d, --changeDefaultModel` flag.
> fix: correct changeDefaultModel flag description

- README.md
It is updating the installation path of to_pdf
https://github.com/danielmiessler/fabric/issues/956
> Updated Path to install to_pdf in readme[Bug Fix]

- README.md
- cli/cli.go
- cli/flags.go
A wipe parameter is added to context and session for cleaning up outdated data
> add wipe flag for ctx and session

- cli/cli.go
- youtube/youtube.go
This PR will match the language of the transcript to the one from the user rather than selecting the first returned from Youtube. Defaults to English if nothing else specified.
closes #1010
> Grab transcript from youtube matching the user's language

- patterns/transcribe_minutes/system.md
Fixed typos and improved consistency of the different sections.
none
> Update system.md in transcribe_minutes

- patterns/analyze_military_strategy/system.md
Use this pattern to analyze real historic, or fictional battle strategy.
Adds a pattern
> Add pattern analyze_military_strategy

- patterns/agility_story/system.md
Changes example output topic name to make sense.
> Update prompt in agility_story

- patterns/transcribe_minutes/system.md
- Changed "agreed within the meeting" to "agreed upon within the meeting" for grammatical accuracy.
- Added missing periods for consistency across list items.
- Corrected the spelling of "highliting" to "highlighting."
- Fixed the spelling of "exxactly" to "exactly."
- Updated phrasing from "Write NEXT STEPS a 2-3 sentences" to "Write NEXT STEPS as 2-3 sentences" for grammatical correctness.
These changes enhance readability and ensure that the document is consistent and free of grammatical errors.
This PR corrects spelling, grammar, and punctuation issues in the document to improve overall clarity and consistency.
> Corrected spelling and grammatical errors for consistency and clarity for transcribe_minutes

- patterns/translate/system.md
This creates a new folder named translate in the pattern folder and adds the system.md file which contains the prompt for basic translation request.
Users will want to edit the system.md file and replace the <Language> with the desired language to be translated to.
I've tested it with a few files created from extract_wisdom and it seemed to work pretty well.
None
None
> Create a basic translator pattern, edit file to add desired language

- patterns/ask_uncle_duke/system.md
- patterns/dialog_with_socrates/system.md
I have created two new patterns:
- Ask Uncle Duke is a Java-centric software development pattern.
- Dialog with Socrates is a conversational pattern for developing critical thinking.
> A couple of patterns.

- patterns/analyze_proposition/system.md
Added pattern to analyze government, state, and local propositions.
> Analyze Proposition Pattern

- patterns/md_callout/system.md
Adds a pattern that can convert text into an appropriate markdown callout
> feat: add md_callout pattern

- cli/cli.go
- cli/flags.go
- common/domain.go
- core/chatter.go
- core/plugin_registry.go
- flake.nix
- gomod2nix.toml
- plugins/ai/dryrun/dryrun.go
- plugins/ai/ollama/ollama.go
- plugins/tools/defaults.go
This PR adds support for setting default Model Context Length.
Motivation:
- I don't want to create a separate extended context model in Ollama just to set the num_ctx parameter, also you can't change it on the fly if you do so.
- This will fix all issues that are caused by Ollama's default 2048 token context window. They are common because Fabric's best patterns like `extract_wisdom`, `summarize` and others almost always require high context window lengths to work on large inputs.
This PR adds:
- `--contextLength` flag to set context length using cli
- `DEFAULT_CONTEXT_LENGTH` option to `.config/fabric/.env` (used if `--contextLength` is not used)
- *if neither `--contextLength` nor `DEFAULT_CONTEXT_LENGTH` are set context parameter is not sent at all*
- `--dry-run` support is included …
> feat: add DEFAULT_CONTEXT_LENGTH setting

- patterns/create_user_story/system.md
A new pattern to help create user stories in agile software teams.
> Create user story pattern

- patterns/create_diy/system.md
Add a new pattern to create do it your self tutorial, you can use this for cooking recipes, tutorials, etc
> Added create_diy

- .devcontainer/devcontainer.json
> Create Selemela07 devcontainer.json

- patterns/analyze_candidates/system.md
Adds a pattern that analyzes candidates.
> Analyze Candidates Pattern

- patterns/summarize_meeting/system.md
Add a new pattern to create a meeting summary from an audio transcript.
The pattern outputs the following sections (where relevant):
- Key Points
- Tasks
- Decisions
- Next Steps
> Add summarize_meeting

- patterns/create_newsletter_entry/system.md
This PR adds a new patter to create a newsletter section on the input text
> added a new pattern create_newsletter_entry

- core/chatter.go
Fixes segfault iss if pattern is used with no user input.
./fabric -p foo
> Curly brace templates

- patterns/analyze_risk/system.md
Created a pattern to analyze 3rd party vendor risk.
Created a folder called analyze_risk within the  pattern directory and then added system.md of pattern to analyze 3rd party vendor risk.
NONE
It ends up looking like this:
> analyze_risk pattern

- README.md
- patterns/analyze_answers/README.md
- patterns/create_quiz/README.md
- patterns/summarize_paper/README.md
Hi! I found couple of spelling issues in README and patterns. Hope that can be fixed in the repo, if you find them relevant.
NA
NA
> Spelling Fixes

- patterns/translate/system.md
> Fix the typo in the sentence

- cli/cli.go
- cli/flags.go
- restapi/ollama.go
Add Endpoints to facilitate Ollama based chats. Include another flag to serve additional endpoints. 
Built to use with Open WebUI
> Add Endpoints to facilitate Ollama based chats

- patterns/humanize/README.md
- patterns/humanize/system.md
Proposing a new pattern for Fabric: **Humanize** 
This pattern aims to help make AI generated text sound more like a real person wrote it.
None
None
> Added Humanize Pattern

- patterns/translate/system.md
Updates the pattern for translation to use curly braces so we can insert the target language as a parameter on the command line, i.e
`$ cat my-english-text.md | fabric -v=lang_code:ja-jp -p translate` 
Resending my PR that removes the version files reference [here].(https://github.com/danielmiessler/fabric/pull/1219)
> Update translate pattern to use curly braces

- README.md
- cli/cli.go
- cli/flags.go
- plugins/tools/youtube/youtube.go
Added metadata lookup to the YouTube helper.
None
```bash
fabric -y "https://www.youtube.com/watch?v=wPEyyigh10g" --metadata
{
"id": "wPEyyigh10g",
"title": "Introducing Fabric — A Human AI Augmentation Framework",
"description": "This video introduces Fabric—an open-source project for augmenting humans using AI. It provides a modular framework for solving specific problems using a crowdsourced set of AI prompts that can be used anywhere.\n\nTOPICS:\n\n00:00:00 Introduction to Fabric\n00:01:24 Human-Centric AI Approach\n00:02:22 Challenges and Solutions\n00:03:59 Fabric Project Overview\n00:04:34 Structure and Components\n00:05:10 Patterns and Prompts\n00:07:11 Extracting Article Wisdom\n00:08:06 Open Source Collaboration\n00:09:02 Analyzing Video Content\n00:11:05 Extract Wisdom …
```
> Adding youtube --metadata flag

- README.md
Adds instructions for creating fabric aliases on Windows hosts using PowerShell.
> Update README.md: Add PowerShell aliases

- README.md
Fixed the pattern claim. Adds web scraping example.
> Minor README fix and additional Example

- patterns/create_loe_document/system.md
Added Create LOE Document Prompt
> Added Create LOE Document Prompt

- WEB INTERFACE MOD README FILES/pr-1284-update.md
Simply updating the video presenting the new functionalities
> Update demo video link in PR-1309 documentation

- WEB INTERFACE MOD README FILES/WEB V2 Install Guide.md
This will help until the web component is fully wrapped up as a Go component.
> Svelte Web V2 Installation Guide

- patterns/extract_wisdom/system.md
The quotes would be more meaningful if it included the name of the speaker. This is especially useful in podcasts.
If it closes an issue, type `closes  #1332`.
> Update QUOTES section to include speaker names for clarity

- Web Interface MOD Readme Files/WEB V2 Install Guide.md
- Web Interface MOD Readme Files/pr-1284-update.md
- web/Web Interface Update README Files/pr-1284-update.md
- web/Web Interface Update README Files/pr-1319_PDF_TO_MARKDOWN_README.md
> Fixed ALL CAP DIR as requested and processed minor updates to documentation

- README.md
- patterns/pattern_explanations.md
- patterns/youtube_summary/system.md
- plugins/tools/youtube/youtube.go
- version.go
This PR adds flexibility to the YouTube transcript command-line functions by introducing an optional timestamp flag and clarifies the usage in both Bash and PowerShell scripts. Additionally, it updates the regex in the YouTube Go plugin to properly match live stream URLs, improves documentation by adding a new pattern explanation, and supplies a full specification for generating concise YouTube summaries from timestamped transcripts.
N/A
Before fix:
```plain
$ yt 'https://www.youtube.com/live/XkFKNkAEzQ8?si=dpbow6CDr6C2cz7R'
invalid YouTube URL, can't get video or playlist ID: 'https://www.youtube.com/live/g4MN5ZPdcG4?si=iCn5EMcKAGLehciA'
```
After fix (with the enhanced `yt` aliases and the `youtube_summary` pattern):
```plain
yt -t …
```
> Fix for youtube live links plus new youtube_summary pattern

- core/plugin_registry.go
- main.go
- plugins/ai/litellm/litellm.go
- Add LiteLLM support which enables [many models/providers](https://docs.litellm.ai/docs/providers)
- Format vendor list a bit without losing content
Closes #1344
Help with below since liteLLM supports them: 
#1347 
#1308
#1033
#517
#435
#310
> feat: Add LiteLLM AI plugin support with local endpoint configuration

- Pattern_Descriptions/pattern_descriptions.json
- web/Web Interface Update README Files/pr-1284-update.md
- web/src/lib/components/chat/Chat.svelte
- web/src/lib/components/home/Header.svelte
- web/src/lib/components/patterns/PatternList.svelte
- web/src/lib/components/patterns/TagFilterPanel.svelte
- web/src/lib/components/ui/modal/Modal.svelte
- web/src/lib/components/ui/modal/PatternTilesModal.svelte
- web/src/lib/components/ui/tooltip/Tooltip.svelte
- web/static/data/pattern_descriptions.json
Added a "Pattern Tile" view in addition to list view as well as implement "column resizing" functionality (eg allow resizing of pattern output window). 
Updated Demo (last min) 
https://youtu.be/fcVitd4Kb98
**PATTERN TILES**
**RESIZING**
**NOTE:**  The GO pull request **test fail** is related to the Azure plugin and unrelated to my changes which are limited to the web modal component implementation. 
* Path: web/src/lib/components/ui/modal/PatternTilesModal.svelte
* Changes:
* Restructured the header with a grid layout
* Pattern tiles display implementation 
* Path: web/src/lib/components/patterns/PatternList.svelte
* Changes:
* Updated the layout to match the reference design
* Improved the selected tags display
* Path: web/src/lib/components/home/Header.svelte
* Changes:
* Improved …
> Implement Pattern Tile search functionality

- Web Interface MOD Readme Files/WEB V2 Install Guide.md
- web/src/lib/components/chat/Chat.svelte
> Fix Chat history window scrolling behavior

- patterns/pattern_explanations.md
> pattern_explanations.md: fix typo

- .gitignore
- Alma.md
No functional changes. Adds `.vscode` for workspace settings to `.gitignore` and fixes some typos and markdown lint problems in `Alma.md`
N/A
N/A
> chore: add .vscode to `.gitignore` and fix typos and markdown linting  in `Alma.md`

- README.md
- requirements.txt
- streamlit.py
Makes copy/paste in the streamlit app work across all platforms (Mac, PC, Linux)
I didn't check
None
ps. 
1 - This is the first time I've ever contributed to anything. Please be kind! Let me know if I've done anything wrong :)
2 - Done using Claude 3.7 Thinking in Cursor
3 - Tested on Mac. Not tested on PC or Linux.
> clipboard operations now work on Mac and PC

- README.md
- Remove colons from heading anchors
- Fix broken installation link reference
- Replace code tags with backticks
- Improve code block formatting with indentation
- Clarify package manager alias requirements
- Fix environment variables link
- Simplify custom patterns directory instructions
Fix some README bugs.
> docs: improve README formatting and fix some broken links

- patterns/find_logical_fallacies/system.md
Fix typo on fallacies instruction.
> Fix typo on fallacies instruction.

- web/src/lib/components/chat/Chat.svelte
- web/src/lib/components/chat/ChatInput.svelte
- web/src/lib/components/chat/ChatMessages.svelte
- web/src/lib/components/chat/DropdownGroup.svelte
Implement possibility to resize the three main windows in the chat interface within safe limits. 
Also fixed an issue pertaining to raw text input not being passed for processing.
> Add flex windows sizing to web interface + raw text input fix

- README.md
- Fix broken what-and-why link reference
> docs: improve README link

- plugins/tools/code_helper/main.go
This PR refactors the `code_helper` tool to improve its command-line interface, error handling, and overall code quality. The changes enforce a more consistent usage pattern by requiring both directory and instructions arguments, while also improving error messages and simplifying the codebase.
Refactored the main CLI implementation to be more robust and user-friendly.
1. **Simplified command-line flags handling**:
- Removed the redundant `-help` flag in favor of the built-in `flag.Usage`
- Set `flag.Usage` to our custom `printUsage` function for better help output
2. **Improved argument validation**:
- Now requires exactly two positional arguments (directory and instructions)
- Previously allowed optional instructions, which could lead to confusion
```go
// Before
if *showHelp || …
```
> chore: enhance argument validation in `code_helper` tool

- completion/fabric.fish
Add a fish shell complete script. This could be generated at some point in the future, but at least is a start.
This was mostly generated by AI with manual adjustments to make to the functions so things like the descriptions of strategy work. If descriptions were added to the `--listpattens` then those could be included as well.
#1130 & #659 - at least for `fish`.
> Add a completion script for fish

- common/groups_items.go
- Add `getSortedGroupsItems` to centralize sorting logic.
- Sort groups and items alphabetically, case-insensitive.
- Replace inline sorting in `Print` with new method.
- Update `GetGroupAndItemByItemNumber` to use sorted data.
- Ensure original `GroupsItems` remains unmodified.
This PR introduces a new method `getSortedGroupsItems` to the `GroupsItemsSelector` struct, which centralizes the logic for sorting groups and their items alphabetically in a case-insensitive manner. The new method is utilized in both `GetGroupAndItemByItemNumber` and `Print` functions to ensure consistent sorting behavior across the codebase.
Closes #1451 
- **common/groups_items.go**: Added a new method for sorting groups and items, and refactored existing functions to use this method instead of duplicating …
> Fix for default model setting

- patterns/create_hormozi_offer/system.md
- Improved formatting of the introduction and content summary sections for better flow.
- Consolidated repetitive sentences and enhanced the overall coherence of the text.
- Adjusted bullet points and numbering for consistency and easier comprehension.
- Ensured that key concepts are clearly articulated and visually distinct to aid understanding.
N/A
N/A
> Refactor content structure in create_hormozi_offer system.md for clarity and readability

- core/chatter.go
- plugins/ai/anthropic/anthropic.go
- plugins/ai/openai/openai.go
This PR does a couple of things:
1. Eliminates the doubled user messages that were being sent (effetcively cutting our token use now by 50%!)
2. Enhances message handling across different AI providers, focusing on proper message formatting for Anthropic's Claude models and improving the handling of system messages in raw mode. The changes ensure more consistent behavior across providers and fix potential issues with empty messages and message role sequencing.
closes #1245 and #1203 
Refactored the message handling logic to properly handle system messages and patterns:
- Fixed how system messages are combined with user messages in raw mode
- Improved handling of patterns by not appending user messages when a pattern is used
- Added proper escaping of newlines in formatted messages
- Added …
> feat: update `BuildSession` to handle message appending logic

- core/chatter.go
- Fix system message handling with patterns in raw mode
- Prevent duplicate inputs when using patterns
- Add conditional logic for pattern vs non-pattern scenarios
- Simplify message construction with clearer variable names
- Improve code comments for better readability
This PR enhances the `BuildSession` method in the `Chatter` component to properly handle raw mode when patterns are used. The changes fix an issue where system messages were being duplicated when a pattern was specified along with raw mode.
closes #1203 
- **core/chatter.go**: Updated the logic in the `BuildSession` method to avoid duplicating content when both raw mode and patterns are used.
The main change is in the raw mode handling section of the `BuildSession` method:
```go
// Before: Simple concatenation that could …
```
> refactor: improve raw mode handling in BuildSession

- patterns/analyze_terraform_plan/system.md
This PR adds a new Fabric pattern for analyzing Terraform plan outputs. The pattern provides structured
analysis of infrastructure changes with a focus on security, cost, and compliance implications.
Copied from https://marksharpley.co.uk/posts/fabric/
Closes #1492 
- New system prompt file that defines the behavior for analyzing Terraform plans
- Establishes the AI assistant's role as an expert Terraform plan analyzer
- Defines a structured output format for consistent analysis results
The file introduces a comprehensive prompt structure:
```markdown
You are an expert Terraform plan analyser. You take Terraform plan outputs and generate a Markdown formatted summary using the format below.
You focus on assessing infrastructure changes, security risks, cost implications, and compliance …
```
> feat: add Terraform plan analyzer pattern for infrastructure changes

- plugins/tools/youtube/youtube.go
This PR modernizes the YouTube transcript extraction by replacing the unreliable web scraping approach with a robust `yt-dlp`-based implementation.
The changes remove the old HTML parsing logic that was prone to breaking due to YouTube's frequent UI changes and instead leverage yt-dlp's stable transcript extraction capabilities.
Closes #1498
Closes #1395 
- **Modified**: Completely refactored the transcript extraction logic
- **Removed**: Dependencies on web scraping (`github.com/anaskhan96/soup`) and manual JSON parsing
- **Added**: Integration with yt-dlp command-line tool for reliable transcript extraction
- **Enhanced**: Added comprehensive documentation explaining the implementation approach
```go
- import "encoding/json"
- import "net/url"
- import "github.com/anaskhan96/soup"
``` …
> Refactor: No more web scraping, just use yt-dlp

- plugins/tools/youtube/youtube.go
This PR enhances the YouTube plugin's cross-platform compatibility by replacing Unix-specific file operations with Go's standard library functions. The main changes involve using `filepath` for path operations and implementing a custom VTT file discovery function that works across different operating systems.
Fixes #1509 
- Added import for `path/filepath` package
- Modified temporary directory creation to use `os.TempDir()` and `filepath.Join()`
- Replaced Unix `find` command with a custom Go function for locating VTT files
- Updated file path construction throughout to use platform-agnostic methods
```go
+       "path/filepath"
```
Added the `filepath` package to handle file paths in a cross-platform manner.
```go
-       tempDir := "/tmp/fabric-youtube-" + videoId
+       tempDir := …
```
> Cross-Platform fix for Youtube Transcript extraction

- patterns/create_mnemonic_phrases/readme.md
- patterns/create_mnemonic_phrases/system.md
This pull request introduces a new pattern for generating mnemonic phrases from Diceware words. It includes three markdown files: `disclaimer.md`, `readme.md`, and `system.md`. These files collectively provide legal disclaimers, an overview of the feature, and implementation details.
**Description**: Provides an overview of the mnemonic phrase creation pattern. It explains its purpose and offers guidance on how to use it.
**Description**: Details how to implement the mnemonic phrase generation. It specifies that given words should be outputted in order and highlighted, followed by five short mnemonic sentences.
The primary motivation behind these changes is to introduce a new functionality that allows users to generate mnemonic phrases from Diceware words. This feature is particularly …
> feat: create mnemonic phrase pattern

- go.mod
- go.sum
- plugins/ai/bedrock/bedrock.go
This PR updates the Bedrock plugin to fetch the available foundation models and inference providers.
The advantage of this approach is that the list of models is correct for the user. The downside is that it involves atleast two network requests/
This is a follow up PR for a change requested in #1512
> feat: Dynamically list AWS Bedrock models

- core/plugin_registry.go
The Bedrock plugin is now initialized only when AWS credentials are found in environment variables or the standard `~/.aws/credentials` file. This is achieved by adding a pre-check function, `hasAWSCredentials()`, which is called before the Bedrock client is added to the list of available vendors.
Closes #1521 
*   `core/plugin_registry.go`: Modified to include the credential check and conditionally register the Bedrock plugin.
A new private helper function, `hasAWSCredentials`, has been added to check for the presence of AWS credentials without validating them.
```go
// core/plugin_registry.go
// hasAWSCredentials checks if any AWS credentials are present either in the
// environment variables or in the default/shared credentials file. It doesn't
// attempt to verify the validity of the …
```
> Conditional AWS Bedrock Plugin Initialization

- core/plugin_registry.go
This PR updates the `hasAWSCredentials` check with some additional environment variables that indicate AWS Credentials are present.
Extends #1523. Addresses #1521
> Check for AWS_PROFILE or AWS_ROLE_SESSION_NAME environment variables

- README.md
- common/domain.go
- core/plugin_registry.go
- go.mod
- go.sum
- plugins/ai/perplexity/perplexity.go
This PR adds support for Perplexity AI as a new AI provider in the Fabric framework. The implementation includes a complete client integration with support for both standard and streaming chat completions, following the existing plugin architecture patterns.
Closes #924 
Closes #1078 
- Updated the release notes to announce Perplexity AI support
- Added example usage command for the new integration
- Reorganized the update notes chronologically
- Added `MaxTokens` field to `ChatOptions` struct to support token limit configuration
- Added import for the new perplexity plugin package
- Registered the Perplexity client in the plugin registry
- Added dependency on `github.com/sgaunet/perplexity-go/v2` v2.8.0 for Perplexity API integration
- Implemented complete Perplexity AI client with …
> Add Perplexity AI Provider with Token Limits Support

- plugins/ai/perplexity/perplexity.go
This PR adds citation support to the Perplexity AI plugin, enabling the display of source citations when the Perplexity API returns them in its responses. The changes modify both the synchronous and streaming response handlers to append formatted citations to the output.
Closes #1529 
- **plugins/ai/perplexity/perplexity.go**: Modified to extract and format citations from Perplexity API responses in both `Send()` and `SendStream()` methods.
```go
-       return resp.GetLastContent(), nil
+       content := resp.GetLastContent()
+
+       // Append citations if available
+       citations := resp.GetCitations()
+       if len(citations) > 0 {
+               content += "\n\n# CITATIONS\n\n"
+               for i, citation := range citations {
+                       content += …
```
> Add Citation Support to Perplexity Response

- plugins/ai/openai_compatible/providers_config.go
This PR introduces dynamic environment variable support for OpenAI-compatible provider configurations, specifically adding template variable substitution in provider base URLs. The changes also reorganize the provider map to be alphabetically sorted and add a new provider (Langdock) that demonstrates the new templating feature.
Closes #1539 
- **`plugins/ai/openai_compatible/providers_config.go`**: Modified to add template variable parsing logic and reorganized provider configurations
```go
+	"os"
+	"strings"
```
Added imports for environment variable access and string manipulation needed for template parsing.
The `ProviderMap` has been alphabetically sorted for better maintainability. Additionally, a new provider "Langdock" has been added:
```go
+	"Langdock": {
+		Name:    "Langdock",
+ …
```
> Add Langdock AI and enhance generic OpenAI compatible support

- README.md
- go.mod
- go.sum
This PR updates the README documentation and dependency versions, focusing on improving clarity, fixing typos, and ensuring consistent formatting throughout the project documentation.
Documentation improvements including:
- Added DeepWiki badge for enhanced project visibility
- Fixed typos and improved clarity in various sections
- Reorganized navigation structure links to match the actual document for better flow
- Added alt text to contributor images for accessibility
- Minor formatting and wording improvements
Dependency management updates:
- Updated `sashabaranov/go-openai` from v1.40.1 to v1.40.3
- Cleaned up module requirements by removing unused `anaskhan96/soup` dependency
- Consolidated AWS SDK dependencies
Key documentation changes:
```markdown
+[![Ask …
```
> docs: add DeepWiki badge and fix minor typos in README

- .github/ISSUE_TEMPLATE/bug.yml
This PR enhances the GitHub issue template for bug reports by adding more detailed fields to collect comprehensive information about the user's environment and installation method. The changes improve the bug reporting process by gathering essential system information upfront, which will help maintainers better understand and reproduce reported issues.
- `.github/ISSUE_TEMPLATE/bug.yml` - Enhanced the bug report template with additional fields for OS information, installation method, and version details.
```yaml
value: |
Thanks for taking the time to fill out this bug report!
Please provide as much detail as possible to help us understand and reproduce the issue.
```
Added clearer instructions encouraging users to provide detailed information.
```yaml
value: "Please provide all the steps …
```
> Enhance bug report template

- plugins/ai/anthropic/anthropic.go
- plugins/ai/anthropic/oauth.go
- plugins/ai/anthropic/oauth_test.go
This PR refactors the OAuth token management system in the Anthropic plugin to use parameterized token identifiers instead of hardcoded values. The changes improve code maintainability, testability, and prepare the foundation for supporting multiple token types or providers in the future.
- **Renamed constant**: Changed `vendorTokenIdentifier` to `authTokenIdentifier` for clearer naming
- **Updated method signatures**: Modified `RunOAuthFlow()` and `RefreshToken()` calls to accept token identifier parameter
- **Consistent token identifier usage**: All OAuth-related calls now use the `authTokenIdentifier` constant
- **Parameterized OAuth functions**: Added `tokenIdentifier` parameter to `RunOAuthFlow()`, `RefreshToken()`, `exchangeToken()`, and `getValidToken()` methods
- **Enhanced token …
> Refactor: Generalize OAuth flow for improved token handling.

- .github/workflows/patterns.yaml
Updated GitHub Actions workflow to reflect the relocation of patterns folder from root directory to `data/patterns/`. This change ensures the CI/CD pipeline correctly monitors and processes pattern files in their new location.
- **.github/workflows/patterns.yaml**: Modified workflow configuration to update all references from `patterns/` to `data/patterns/` to align with the new directory structure.
The following changes were made to the workflow file:
**Trigger path updated:**
```yaml
- "patterns/**"
- "data/patterns/**"
```
**Git diff verification updated:**
```bash
if git diff --quiet HEAD~1 -- patterns; then
if git diff --quiet HEAD~1 -- data/patterns; then
```
**Zip command updated:**
```bash
run: zip -r patterns.zip patterns/
run: zip -r patterns.zip data/patterns/
```
This update …
> Fix patterns zipping workflow

- flake.nix
- nix/pkgs/fabric/default.nix
- nix/shell.nix
- rename `update` helper to `update-mod`
- fix `gomod2nix.toml` generation path when when using `update-mod` helper from nix shell.
- use self reference for getting package sources.
> Flake: fixes and enhancements

- data/patterns/t_analyze_challenge_handling/system.md
- data/patterns/t_check_metrics/system.md
- data/patterns/t_create_h3_career/system.md
- data/patterns/t_create_opening_sentences/system.md
- data/patterns/t_describe_life_outlook/system.md
- data/patterns/t_extract_intro_sentences/system.md
- data/patterns/t_extract_panel_topics/system.md
- data/patterns/t_find_blindspots/system.md
- data/patterns/t_find_negative_thinking/system.md
- data/patterns/t_find_neglected_goals/system.md
- data/patterns/t_give_encouragement/system.md
- data/patterns/t_red_team_thinking/system.md
- data/patterns/t_threat_model_plans/system.md
- data/patterns/t_visualize_mission_goals_projects/system.md
- data/patterns/t_year_in_review/system.md
There are typos in some of the TELOS patterns - ouptut instead of output
No issues.
> Fix typos in t_ patterns

- data/patterns/write_hackerone_report/system.md
- internal/plugins/ai/bedrock/bedrock.go
> chore: remove redundant words

- .vscode/settings.json
- README.md
- cmd/generate_changelog/incoming/1709.txt
- internal/tools/youtube/youtube.go
This PR improves YouTube subtitle language fallback handling in the yt-dlp integration, allowing for more flexible subtitle selection when the exact language match is not available. Additionally, it includes minor documentation and configuration fixes.
Closes #1237 
- **`.vscode/settings.json`**: Added new words to the VSCode spell checker dictionary
- **`README.md`**: Fixed a typo in the feature list
- **`cmd/generate_changelog/incoming/1709.txt`**: Added changelog entry for this PR
- **`internal/tools/youtube/youtube.go`**: Enhanced subtitle language fallback logic
The main change improves how yt-dlp handles subtitle language selection:
```go
// Before:
args = append(args, "--sub-langs", langMatch)
// After:
langOpts := language + "," + langMatch + ".*," + langMatch
args = append(args, …
```
> Enhanced YouTube Subtitle Language Fallback Handling

- README.md
- cmd/generate_changelog/incoming/1714.txt
- internal/cli/chat.go
This PR adds per-pattern model mapping support to the Fabric CLI tool, allowing users to configure specific AI models for individual patterns using environment variables. This enhancement provides more granular control over model selection without requiring command-line flags for each pattern usage.
Closes #691
- **README.md**: Added documentation for the new per-pattern model mapping feature
- **internal/cli/chat.go**: Implemented the core functionality for environment variable-based model mapping
The main implementation adds environment variable lookup logic in the `handleChatProcessing` function:
```go
// Check for pattern-specific model via environment variable
if currentFlags.Pattern != "" && currentFlags.Model == "" {
envVar := "FABRIC_MODEL_" + …
```
> Add Per-Pattern Model Mapping via Environment Variables

- cmd/generate_changelog/incoming/1731.txt
- go.mod
- go.sum
Updated the Ollama dependency from version 0.9.0 to 0.11.7 to incorporate the latest features, improvements, and bug fixes from the upstream library.
- **go.mod**: Updated the Ollama package version requirement from v0.9.0 to v0.11.7
- **go.sum**: Updated checksums to reflect the new Ollama package version and its dependencies
```diff
-	github.com/ollama/ollama v0.9.0
+	github.com/ollama/ollama v0.11.7
```
```diff
-github.com/ollama/ollama v0.9.0 h1:GvdGhi8G/QMnFrY0TMLDy1bXua+Ify8KTkFe4ZY/OZs=
-github.com/ollama/ollama v0.9.0/go.mod h1:aio9yQ7nc4uwIbn6S0LkGEPgn8/9bNQLL1nHuH+OcD0=
+github.com/ollama/ollama v0.11.7 h1:CuYjaJ/YEnvLDpJocJbbVdpdVFyGA/OP6lKFyzZD4dI=
+github.com/ollama/ollama v0.11.7/go.mod h1:9+1//yWPsDE2u+l1a5mpaKrYw4VdnSsRU3ioq5BvMms=
```
This dependency update brings the …
> chore: upgrade ollama dependency from v0.9.0 to v0.11.7

- .github/workflows/release.yml
- cmd/generate_changelog/incoming/1740.txt
- cmd/generate_changelog/internal/release.go
This was unintentionally removed when we simplified our release process by adding GoReleaser.
This pull request enhances the release workflow by adding back in the automatic changelog generation and improves the release description update logic to handle forked repositories. The changes add a new step to the GitHub Actions workflow that generates and updates release descriptions, while also implementing fork-aware repository handling in the release manager.
- **Added**: New workflow step "Update Release Description" that runs after the GoReleaser step
- **Purpose**: Automatically generates and updates release descriptions using the changelog generator tool
- **Modified**: Enhanced `UpdateReleaseDescription` method with fork detection and handling
- **Added**: New helper method …
> Restore our custom Changelog Updates in GitHub Actions
